"""OpenAPI 唯一生成入口的低层反例。"""

from __future__ import annotations

import importlib.util
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from unittest import mock
from pathlib import Path
from typing import Callable


SCRIPT = Path(__file__).resolve().parents[1] / "generate-openapi-contracts.py"
SPEC = importlib.util.spec_from_file_location("generate_openapi_contracts", SCRIPT)
assert SPEC is not None and SPEC.loader is not None
GENERATOR = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = GENERATOR
SPEC.loader.exec_module(GENERATOR)


VALID_OPENAPI = '{"openapi":"3.1.0","paths":{},"components":{}}\n'
VALID_SCHEMA = """/**
 * This file was auto-generated by openapi-typescript.
 */
export interface paths {}
"""


class FakeGenerationRunner:
    """模拟 Maven 与 Node 生成器，并允许在阶段边界注入竞争。"""

    def __init__(
        self,
        *,
        fail_backend: bool = False,
        fail_console: bool = False,
        openapi: str = VALID_OPENAPI,
        schema: str = VALID_SCHEMA,
        after_backend: Callable[[], None] | None = None,
        after_console: Callable[[], None] | None = None,
    ) -> None:
        self.fail_backend = fail_backend
        self.fail_console = fail_console
        self.openapi = openapi
        self.schema = schema
        self.after_backend = after_backend
        self.after_console = after_console
        self.calls: list[tuple[tuple[str, ...], Path, dict[str, str]]] = []

    def __call__(self, command: list[str], cwd: Path, environment: dict[str, str]) -> None:
        """按命令形状写入对应暂存文件。"""

        self.calls.append((tuple(command), cwd, dict(environment)))
        if any(argument == "-Dtest=OpenApiSpecTests" for argument in command):
            if self.fail_backend:
                raise GENERATOR.GenerationError("受控 Maven 失败")
            output_argument = next(
                argument for argument in command if argument.startswith("-Dopenapi.output=")
            )
            Path(output_argument.split("=", 1)[1]).write_text(self.openapi, encoding="utf-8", newline="")
            if self.after_backend is not None:
                self.after_backend()
            return

        if command[0] == "node":
            if self.fail_console:
                raise GENERATOR.GenerationError("受控 Console 失败")
            output = Path(command[command.index("-o") + 1])
            output.write_text(self.schema, encoding="utf-8", newline="")
            if self.after_console is not None:
                self.after_console()
            return

        raise AssertionError(f"未知命令：{command}")


class OpenApiContractGenerationTests(unittest.TestCase):
    """验证冲突、失败、漂移和成功发布边界。"""

    def setUp(self) -> None:
        """创建不依赖真实 Maven、Node 或网络的临时 Git 仓。"""

        self.temporary = tempfile.TemporaryDirectory(prefix="openapi-generation-tests-")
        self.repository = Path(self.temporary.name)
        self.backend = self.repository / "things-link"
        self.console = self.repository / "things-link-console"
        self.openapi = self.repository / "docs/openapi.json"
        self.schema = self.console / "src/types/api/schema.d.ts"
        self.source = self.backend / "sample/src/main/java/example/Api.java"

        (self.backend / ".mvn/wrapper").mkdir(parents=True)
        self.source.parent.mkdir(parents=True)
        (self.console / "node_modules/openapi-typescript/bin").mkdir(parents=True)
        self.openapi.parent.mkdir(parents=True)
        self.schema.parent.mkdir(parents=True)
        (self.repository / "scripts").mkdir(parents=True)

        (self.backend / "mvnw").write_text("#!/bin/sh\n", encoding="utf-8", newline="")
        (self.backend / "mvnw.cmd").write_text("@echo off\r\n", encoding="utf-8", newline="")
        (self.backend / "pom.xml").write_text("<project/>\n", encoding="utf-8", newline="")
        self.source.write_text("final class Api {}\n", encoding="utf-8", newline="")
        (self.console / "package.json").write_text(
            '{"name":"fixture","scripts":{"api:generate":'
            '"python3 ../scripts/generate-openapi-contracts.py"}}\n',
            encoding="utf-8",
        )
        (self.console / "pnpm-lock.yaml").write_text(
            "lockfileVersion: '9.0'\n"
            "importers:\n"
            "  .:\n"
            "    devDependencies:\n"
            "      openapi-typescript:\n"
            "        specifier: ^7.13.0\n"
            "        version: 7.13.0(typescript@5.6.3)\n",
            encoding="utf-8",
        )
        (self.console / "node_modules/openapi-typescript/package.json").write_text(
            '{"name":"openapi-typescript","version":"7.13.0"}\n', encoding="utf-8", newline=""
        )
        (self.console / "node_modules/openapi-typescript/bin/cli.js").write_text(
            "// fixture\n", encoding="utf-8", newline=""
        )
        (self.repository / "scripts/generate-openapi-contracts.py").write_text(
            "# fixture generator\n", encoding="utf-8", newline=""
        )
        self.openapi.write_text("old-openapi\n", encoding="utf-8", newline="")
        self.schema.write_text("old-schema\n", encoding="utf-8", newline="")

        # 第二消费端使用独立安装/锁文件，缺失该工程不能被生成器静默跳过。
        self.webapp = self.repository / "things-link-webapp"
        shutil.copytree(self.console, self.webapp)
        self.webapp_schema = self.webapp / "src/types/api/schema.d.ts"

        self.git("init", "-q")
        self.git("config", "user.name", "OpenAPI Tests")
        self.git("config", "user.email", "openapi-tests@example.invalid")
        self.git("add", ".")
        self.git("commit", "-qm", "test: initialize fixture")

    def tearDown(self) -> None:
        """删除临时仓与生成残留。"""

        self.temporary.cleanup()

    def git(self, *arguments: str) -> None:
        """执行临时仓所需的最小 Git 操作。"""

        subprocess.run(
            ["git", *arguments],
            cwd=self.repository,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )

    def original_outputs(self) -> tuple[bytes, bytes, bytes]:
        """返回三个权威目标的当前字节。"""

        return self.openapi.read_bytes(), self.schema.read_bytes(), self.webapp_schema.read_bytes()

    def assert_no_temporary_generation_directory(self) -> None:
        """确认成功和失败都清除了本片暂存目录。"""

        self.assertEqual([], list(self.repository.glob(".openapi-generation-*")))

    def test_ignored_independent_console_lock_drift_rejects_publication(self) -> None:
        self.git("rm", "-r", "--cached", "things-link-console")
        (self.repository / ".gitignore").write_text("things-link-console/\n")
        subprocess.run(["git", "init", "-q", str(self.console)], check=True)
        originals = self.original_outputs()
        lock = self.console / "pnpm-lock.yaml"
        def drift() -> None:
            lock.write_text(lock.read_text() + "# concurrent dependency change\n")
        with self.assertRaises(GENERATOR.GenerationError):
            GENERATOR.generate_contracts(self.repository,
                                         command_runner=FakeGenerationRunner(after_backend=drift))
        self.assertEqual(originals, self.original_outputs())

    def test_success_uses_reactor_and_matching_lease_then_publishes_both(self) -> None:
        """成功路径绑定 reactor、同一租约令牌与两个生成物。"""

        runner = FakeGenerationRunner()
        result = GENERATOR.generate_contracts(self.repository, command_runner=runner)

        self.assertEqual(VALID_OPENAPI, self.openapi.read_text(encoding="utf-8"))
        self.assertEqual(VALID_SCHEMA, self.schema.read_text(encoding="utf-8"))
        self.assertEqual(3, len(runner.calls))
        backend_command, backend_cwd, backend_environment = runner.calls[0]
        self.assertEqual(self.backend.resolve(), backend_cwd)
        self.assertIn("-am", backend_command)
        self.assertLess(backend_command.index("clean"), backend_command.index("test"))
        token_argument = next(
            value for value in backend_command if value.startswith("-Dopenapi.write.lease-token=")
        )
        token = token_argument.split("=", 1)[1]
        self.assertEqual(token, backend_environment["THINGS_LINK_OPENAPI_WRITE_LEASE_TOKEN"])
        staged_openapi = Path(
            next(
                value for value in backend_command if value.startswith("-Dopenapi.output=")
            ).split("=", 1)[1]
        )
        console_command = runner.calls[1][0]
        self.assertEqual(staged_openapi, Path(console_command[2]))
        self.assertNotEqual(self.openapi, Path(console_command[2]))
        self.assertEqual(GENERATOR.sha256_file(self.openapi), result.openapi_sha256)
        self.assertEqual(GENERATOR.sha256_file(self.schema), result.console_schema_sha256)
        self.assertEqual(VALID_SCHEMA, self.webapp_schema.read_text(encoding="utf-8"))
        self.assertEqual(GENERATOR.sha256_file(self.webapp_schema), result.webapp_schema_sha256)
        self.assert_no_temporary_generation_directory()

    def test_semantically_equal_openapi_keeps_baseline_bytes(self) -> None:
        """仅对象成员顺序变化时不得制造契约与类型重排。"""

        baseline = self.repository / "baseline.json"
        staged = self.repository / "staged.json"
        baseline.write_text(
            '{\n  "openapi": "3.1.0",\n  "paths": {},\n  "components": {}\n}\n',
            encoding="utf-8",
        )
        staged.write_text(
            '{"components":{},"paths":{},"openapi":"3.1.0"}\n',
            encoding="utf-8",
        )

        self.assertTrue(GENERATOR.preserve_semantically_equal_openapi(staged, baseline))
        self.assertEqual(baseline.read_bytes(), staged.read_bytes())

    def test_json_boolean_and_numbers_are_not_semantically_interchangeable(self) -> None:
        """布尔、整数和小数即使Python普通相等，也必须形成不同OpenAPI候选。"""

        self.assertFalse(GENERATOR.json_values_identical(True, 1))
        self.assertFalse(GENERATOR.json_values_identical(1, 1.0))

    def test_duplicate_key_openapi_is_rejected(self) -> None:
        """重复键不得被last-wins解析成看似合法的契约。"""

        staged = self.repository / "duplicate-openapi.json"
        staged.write_text(
            '{"openapi":"3.1.0","paths":{},"paths":{},"components":{}}\n',
            encoding="utf-8",
        )

        with self.assertRaisesRegex(GENERATOR.GenerationError, "重复键：paths"):
            GENERATOR.validate_staged_openapi(staged)

    def test_console_generation_alias_cannot_restore_an_independent_writer(self) -> None:
        """消费端公开脚本若绕过根入口，应在取得租约和运行生成器前失败。"""

        (self.console / "package.json").write_text(
            '{"name":"fixture","scripts":{"api:generate":'
            '"openapi-typescript ../docs/openapi.json -o src/types/api/schema.d.ts"}}\n',
            encoding="utf-8",
        )
        runner = FakeGenerationRunner()
        original = self.original_outputs()

        with self.assertRaisesRegex(GENERATOR.GenerationError, "必须委托OpenAPI根入口"):
            GENERATOR.generate_contracts(self.repository, command_runner=runner)

        self.assertEqual([], runner.calls)
        self.assertEqual(original, self.original_outputs())

    def test_repository_console_alias_is_registered_to_the_root_writer(self) -> None:
        """CI直接锁定真实仓库的Console兼容别名，不能只验证临时fixture。"""

        repository = SCRIPT.parents[1]
        for consumer in GENERATOR.CONSUMER_DIRECTORIES:
            GENERATOR.validate_consumer_registration(repository / consumer)

    def test_static_registration_check_does_not_require_installed_dependencies(self) -> None:
        """干净CI检出可审查别名和锁版本，不把node_modules当成仓库事实。"""

        shutil.rmtree(self.console / "node_modules")
        self.assertEqual("7.13.0", GENERATOR.validate_consumer_registration(self.console))

    def test_alias_changed_after_identity_capture_is_rejected_inside_lease(self) -> None:
        """候选冻结后才发生的独立写入口变化也必须在运行生成器前失败。"""

        original_identity = GENERATOR.candidate_identity

        def capture_then_break_alias(repository: Path, targets: tuple[Path, ...]):
            identity = original_identity(repository, targets)
            (self.console / "package.json").write_text(
                '{"name":"fixture","scripts":{"api:generate":"raw-writer"}}\n',
                encoding="utf-8",
            )
            return identity

        runner = FakeGenerationRunner()
        with mock.patch.object(GENERATOR, "candidate_identity", capture_then_break_alias):
            with self.assertRaisesRegex(GENERATOR.GenerationError, "必须委托OpenAPI根入口"):
                GENERATOR.generate_contracts(self.repository, command_runner=runner)

        self.assertEqual([], runner.calls)

    def test_installed_generator_version_must_match_lockfile(self) -> None:
        """陈旧node_modules不能用与锁文件不同的生成器发布类型。"""

        (self.console / "node_modules/openapi-typescript/package.json").write_text(
            '{"name":"openapi-typescript","version":"7.12.0"}\n', encoding="utf-8", newline=""
        )
        runner = FakeGenerationRunner()

        with self.assertRaisesRegex(GENERATOR.GenerationError, "与pnpm锁文件不一致"):
            GENERATOR.generate_contracts(self.repository, command_runner=runner)

        self.assertEqual([], runner.calls)

    def test_held_lease_fails_immediately_without_running_generators(self) -> None:
        """同一工作树已有写者时不等待也不触碰目标。"""

        runner = FakeGenerationRunner()
        original = self.original_outputs()
        with GENERATOR.exclusive_generation_lease(self.repository, "existing-token"):
            with self.assertRaises(GENERATOR.LeaseConflict):
                GENERATOR.generate_contracts(self.repository, command_runner=runner)

        self.assertEqual([], runner.calls)
        self.assertEqual(original, self.original_outputs())

    def test_backend_failure_keeps_both_targets_unchanged(self) -> None:
        """后端生成失败不得留下半套契约。"""

        original = self.original_outputs()
        with self.assertRaisesRegex(GENERATOR.GenerationError, "受控 Maven 失败"):
            GENERATOR.generate_contracts(
                self.repository,
                command_runner=FakeGenerationRunner(fail_backend=True),
            )

        self.assertEqual(original, self.original_outputs())
        self.assert_no_temporary_generation_directory()

    def test_console_failure_keeps_both_targets_unchanged(self) -> None:
        """消费端生成失败时暂存 OpenAPI 不能提前发布。"""

        original = self.original_outputs()
        with self.assertRaisesRegex(GENERATOR.GenerationError, "受控 Console 失败"):
            GENERATOR.generate_contracts(
                self.repository,
                command_runner=FakeGenerationRunner(fail_console=True),
            )

        self.assertEqual(original, self.original_outputs())
        self.assert_no_temporary_generation_directory()

    def test_invalid_console_schema_keeps_both_targets_unchanged(self) -> None:
        """缺少生成器标识的空壳类型不得与暂存OpenAPI一起发布。"""

        original = self.original_outputs()
        with self.assertRaisesRegex(GENERATOR.GenerationError, "缺少 openapi-typescript 生成标识"):
            GENERATOR.generate_contracts(
                self.repository,
                command_runner=FakeGenerationRunner(schema="export interface paths {}\n"),
            )

        self.assertEqual(original, self.original_outputs())
        self.assert_no_temporary_generation_directory()

    def test_invalid_staged_openapi_is_rejected_before_consumer_generation(self) -> None:
        """合法 JSON 错误响应也不能覆盖权威契约。"""

        runner = FakeGenerationRunner(openapi='{"code":90000}\n')
        original = self.original_outputs()
        with self.assertRaisesRegex(GENERATOR.GenerationError, "不是 OpenAPI 3.1"):
            GENERATOR.generate_contracts(self.repository, command_runner=runner)

        self.assertEqual(1, len(runner.calls))
        self.assertEqual(original, self.original_outputs())

    def test_related_input_drift_rejects_stale_candidate(self) -> None:
        """生成中未提交 Controller 输入变化时拒绝旧候选。"""

        runner = FakeGenerationRunner(
            after_console=lambda: self.source.write_text(
                "final class Api { int changed; }\n", encoding="utf-8"
            )
        )
        original = self.original_outputs()
        with self.assertRaisesRegex(GENERATOR.GenerationError, "工作树输入已变化"):
            GENERATOR.generate_contracts(self.repository, command_runner=runner)

        self.assertEqual(original, self.original_outputs())

    def test_target_cas_conflict_does_not_overwrite_other_writer(self) -> None:
        """未遵循租约的目标改写仍由起始摘要 CAS 拒绝覆盖。"""

        runner = FakeGenerationRunner(
            after_console=lambda: self.openapi.write_text("other-writer\n", encoding="utf-8", newline="")
        )
        original_schema = self.schema.read_bytes()
        with self.assertRaisesRegex(GENERATOR.GenerationError, "CAS 冲突"):
            GENERATOR.generate_contracts(self.repository, command_runner=runner)

        self.assertEqual(b"other-writer\n", self.openapi.read_bytes())
        self.assertEqual(original_schema, self.schema.read_bytes())

    def test_symbolic_link_target_is_rejected_before_generation(self) -> None:
        """目标文件符号链接不得把最终发布重定向到另一个节点。"""

        external = self.repository / "external-openapi.json"
        external.write_text("external\n", encoding="utf-8", newline="")
        self.openapi.unlink()
        try:
            self.openapi.symlink_to(external)
        except (OSError, NotImplementedError) as exception:
            self.skipTest(f"当前文件系统不支持符号链接：{exception}")
        runner = FakeGenerationRunner()

        with self.assertRaisesRegex(GENERATOR.GenerationError, "符号链接"):
            GENERATOR.generate_contracts(self.repository, command_runner=runner)

        self.assertEqual([], runner.calls)
        self.assertEqual("external\n", external.read_text(encoding="utf-8"))

    def test_symbolic_link_parent_is_rejected_before_generation(self) -> None:
        """目标父目录符号链接不得把原子替换落到仓库其他位置或仓外。"""

        actual_docs = self.repository / "actual-docs"
        self.openapi.parent.rename(actual_docs)
        try:
            self.openapi.parent.symlink_to(actual_docs, target_is_directory=True)
        except (OSError, NotImplementedError) as exception:
            self.skipTest(f"当前文件系统不支持目录符号链接：{exception}")
        runner = FakeGenerationRunner()

        with self.assertRaisesRegex(GENERATOR.GenerationError, "符号链接"):
            GENERATOR.generate_contracts(self.repository, command_runner=runner)

        self.assertEqual([], runner.calls)
        self.assertEqual("old-openapi\n", (actual_docs / "openapi.json").read_text(encoding="utf-8"))

    def test_second_replace_failure_rolls_back_first_target(self) -> None:
        """第二个文件发布失败时恢复已经替换的第一个文件。"""

        original = self.original_outputs()
        calls = 0

        def fail_second_replace(source: os.PathLike[str], target: os.PathLike[str]) -> None:
            nonlocal calls
            calls += 1
            if calls == 2:
                raise OSError("controlled second replace failure")
            os.replace(source, target)

        with self.assertRaisesRegex(GENERATOR.GenerationError, "controlled second replace failure"):
            GENERATOR.generate_contracts(
                self.repository,
                command_runner=FakeGenerationRunner(),
                replace_file=fail_second_replace,
            )

        self.assertEqual(3, calls)
        self.assertEqual(original, self.original_outputs())
        self.assert_no_temporary_generation_directory()

    def test_input_drift_during_publish_rolls_back_both_targets(self) -> None:
        """发布窄窗口内生产输入变化也会在锁内回滚。"""

        original = self.original_outputs()
        calls = 0

        def drift_after_publish(source: os.PathLike[str], target: os.PathLike[str]) -> None:
            nonlocal calls
            calls += 1
            os.replace(source, target)
            if calls == 2:
                self.source.write_text("final class Api { int late; }\n", encoding="utf-8", newline="")

        with self.assertRaisesRegex(GENERATOR.GenerationError, "发布期间相关工作树输入已变化"):
            GENERATOR.generate_contracts(
                self.repository,
                command_runner=FakeGenerationRunner(),
                replace_file=drift_after_publish,
            )

        self.assertEqual(6, calls)
        self.assertEqual(original, self.original_outputs())
        self.assert_no_temporary_generation_directory()

    def test_webapp_failure_keeps_all_three_outputs(self) -> None:
        """第二消费端生成失败不得留下已生成的Console/OpenAPI半套发布。"""
        original = self.original_outputs()
        successful = FakeGenerationRunner()
        def reject_webapp(command, cwd, environment):
            if cwd == self.webapp.resolve():
                raise GENERATOR.GenerationError("controlled webapp failure")
            successful(command, cwd, environment)
        with self.assertRaisesRegex(GENERATOR.GenerationError, "controlled webapp failure"):
            GENERATOR.generate_contracts(self.repository, command_runner=reject_webapp)
        self.assertEqual(original, self.original_outputs())
        self.assert_no_temporary_generation_directory()

    def test_missing_registered_webapp_is_not_silently_skipped(self) -> None:
        """显式登记消费端缺失是配置故障，不允许退回两份生成物的旧结果。"""
        shutil.rmtree(self.webapp)
        with self.assertRaisesRegex(GENERATOR.GenerationError, "things-link-webapp"):
            GENERATOR.generate_contracts(self.repository, command_runner=FakeGenerationRunner())

    def test_webapp_input_drift_is_in_candidate_digest(self) -> None:
        """新消费端自身锁文件也必须进入源候选摘要。"""
        original = self.original_outputs()
        runner = FakeGenerationRunner(after_console=lambda: (self.webapp / "pnpm-lock.yaml").write_text("drift"))
        with self.assertRaisesRegex(GENERATOR.GenerationError, "输入已变化"):
            GENERATOR.generate_contracts(self.repository, command_runner=runner)
        self.assertEqual(original, self.original_outputs())

    def test_third_target_failure_restores_first_two(self) -> None:
        """新第三目标写入失败恢复已发布的前两份，并保留原WebApp类型。"""
        original = self.original_outputs()
        def reject_third(source, target):
            if Path(target) == self.webapp_schema.resolve():
                raise OSError("controlled third target failure")
            os.replace(source, target)
        with self.assertRaisesRegex(GENERATOR.GenerationError, "third target failure"):
            GENERATOR.generate_contracts(self.repository, command_runner=FakeGenerationRunner(), replace_file=reject_third)
        self.assertEqual(original, self.original_outputs())

    def test_released_os_lock_can_be_reacquired(self) -> None:
        """失败后锁由内核释放，不依赖删除易残留的锁文件。"""

        first = FakeGenerationRunner(fail_backend=True)
        with self.assertRaises(GENERATOR.GenerationError):
            GENERATOR.generate_contracts(self.repository, command_runner=first)

        second = FakeGenerationRunner()
        GENERATOR.generate_contracts(self.repository, command_runner=second)
        self.assertEqual(3, len(second.calls))

    def test_missing_external_command_has_bounded_error(self) -> None:
        """外部运行时缺失时返回稳定生成错误，而不是泄漏底层回溯。"""

        with self.assertRaisesRegex(GENERATOR.GenerationError, "无法启动生成步骤"):
            GENERATOR.run_checked(
                [str(self.repository / "missing-generator")],
                self.repository,
                os.environ,
            )


if __name__ == "__main__":
    unittest.main()
