package com.things.link.bootstrap.integration;
import com.things.link.integration.application.*;
import com.things.link.shared.error.BusinessException;
import com.things.link.shared.id.Uuid7;
import com.things.link.support.tenant.TransactionLocalRlsScope;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.DataAccessException;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import java.util.*;
import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.*;
class WebhookSubscriptionTests extends WebhookFixture {
    @Test void firstSecretOnlyAndOperationRecoveryNeverRevealsStoredSecret(){var op=Uuid7.generate();var first=create(op);assertThat(first.signingSecret()).isNotBlank();assertThat(Base64.getDecoder().decode(first.signingSecret())).hasSize(32);assertThat(first.toString()).doesNotContain(first.signingSecret());
        var replay=create(op);assertThat(replay.replayed()).isTrue();assertThat(replay.signingSecret()).isNull();assertThat(replay.subscription().id()).isEqualTo(first.subscription().id());assertThat(service.recover(tenant,project,account,op).resultRevision()).isEqualTo("1");
        assertThatThrownBy(()->service.create(tenant,project,account,op,new WebhookSubscriptionService.Spec("different",spec().targetUrl(),spec().eventTypes(),spec().deviceIds()))).isInstanceOf(BusinessException.class);
        assertThat(rows("integ_webhook_subscription")).isEqualTo(1);assertThat(rows("integ_webhook_operation")).isEqualTo(1);
        assertThat(owner.queryForObject("SELECT to_jsonb(r)::text FROM integ_webhook_revision r WHERE project_id=?",String.class,project)).doesNotContain(first.signingSecret(),"AQIDBAUGBwgJCgsMDQ4PEBESExQVFhcYGRobHB0eHyA=");
    }
    @Test void revisionsPauseResumeTargetRotationAndTerminalRevoke(){var first=create(Uuid7.generate());UUID id=first.subscription().id();assertThat(change(id,1,"PAUSE").subscription().status()).isEqualTo("PAUSED");assertThat(change(id,2,"RESUME").subscription().revision()).isEqualTo("3");
        var rotated=change(id,3,"ROTATE");assertThat(rotated.signingSecret()).isNotEqualTo(first.signingSecret());
        var moved=service.change(tenant,project,account,Uuid7.generate(),id,4,"UPDATE",new WebhookSubscriptionService.Spec("new","https://other.example.com/events",spec().eventTypes(),spec().deviceIds()));assertThat(moved.signingSecret()).isNotEqualTo(rotated.signingSecret());
        assertThat(change(id,5,"REVOKE").subscription().status()).isEqualTo("REVOKED");assertThatThrownBy(()->change(id,6,"RESUME")).isInstanceOf(BusinessException.class);assertThat(rows("integ_webhook_revision")).isEqualTo(6);
    }
    @Test void concurrentExpectedRevisionAllowsExactlyOneMutation()throws Exception{UUID id=create(Uuid7.generate()).subscription().id();try(var pool=Executors.newVirtualThreadPerTaskExecutor()){var start=new CountDownLatch(1);var results=new ArrayList<Future<Boolean>>();for(int n=0;n<12;n++)results.add(pool.submit(()->{start.await();try{change(id,1,"PAUSE");return true;}catch(BusinessException failure){assertThat(failure.errorCode().code()).isEqualTo(10009);return false;}}));start.countDown();int successes=0;for(var result:results)if(result.get(20,TimeUnit.SECONDS))successes++;assertThat(successes).isEqualTo(1);}assertThat(rows("integ_webhook_revision")).isEqualTo(2);}
    @Test void twentyActiveLimitIsCrossConnectionAtomic()throws Exception{try(var pool=Executors.newVirtualThreadPerTaskExecutor()){var start=new CountDownLatch(1);var results=new ArrayList<Future<Boolean>>();for(int n=0;n<24;n++)results.add(pool.submit(()->{start.await();try{create(Uuid7.generate());return true;}catch(BusinessException failure){assertThat(failure.errorCode().code()).isEqualTo(10029);return false;}}));start.countDown();int successes=0;for(var result:results)if(result.get(30,TimeUnit.SECONDS))successes++;assertThat(successes).isEqualTo(20);}assertThat(rows("integ_webhook_subscription")).isEqualTo(20);assertThat(rows("integ_webhook_operation")).isEqualTo(20);}
    @Test void pausedSubscriptionsStillConsumeHundredNonRevokedBudget(){UUID first=null;for(int i=0;i<100;i++){var value=create(Uuid7.generate()).subscription();if(first==null)first=value.id();change(value.id(),1,"PAUSE");}assertThatThrownBy(()->create(Uuid7.generate())).isInstanceOfSatisfying(BusinessException.class,e->assertThat(e.errorCode().code()).isEqualTo(10029));change(first,2,"REVOKE");assertThat(create(Uuid7.generate()).subscription().status()).isEqualTo("ACTIVE");}
    @Test void dualRlsAndImmutableHistoryAndNoAppDelete(){var value=create(Uuid7.generate());UUID id=value.subscription().id();assertThat(tx.<Integer>execute(s->{rls.establish(tenant,project);return jdbc.queryForObject("SELECT count(*) FROM integ_webhook_revision",Integer.class);})).isEqualTo(1);assertThat(tx.<Integer>execute(s->{rls.establish(UUID.randomUUID(),project);return jdbc.queryForObject("SELECT count(*) FROM integ_webhook_revision",Integer.class);})).isZero();assertThat(tx.<Integer>execute(s->{rls.establish(tenant,UUID.randomUUID());return jdbc.queryForObject("SELECT count(*) FROM integ_webhook_subscription",Integer.class);})).isZero();
        assertThatThrownBy(()->owner.update("UPDATE integ_webhook_revision SET name='mutated' WHERE subscription_id=?",id)).isInstanceOf(DataAccessException.class);assertThatThrownBy(()->owner.update("UPDATE integ_webhook_subscription SET project_generation=1,current_revision=2 WHERE id=?",id)).isInstanceOf(DataAccessException.class);
        assertThatThrownBy(()->tx.execute(s->{rls.establish(tenant,project);jdbc.update("DELETE FROM integ_webhook_revision WHERE subscription_id=?",id);return null;})).isInstanceOf(DataAccessException.class);
        assertThatThrownBy(()->owner.update("UPDATE integ_webhook_operation SET kind='PAUSE' WHERE project_id=?",project)).isInstanceOf(DataAccessException.class);
    }
    @Test void currentRoleAccountTenantAndDeviceCannotBeAssumed(){var first=create(Uuid7.generate());owner.update("UPDATE sys_project_member SET role='VIEWER' WHERE project_id=?",project);assertThatThrownBy(()->service.get(tenant,project,account,first.subscription().id())).isInstanceOf(BusinessException.class);owner.update("UPDATE sys_project_member SET role='OWNER' WHERE project_id=?",project);
        assertThatThrownBy(()->service.create(UUID.randomUUID(),project,account,Uuid7.generate(),spec())).isInstanceOf(BusinessException.class);
        assertThatThrownBy(()->service.create(tenant,project,account,Uuid7.generate(),new WebhookSubscriptionService.Spec("foreign",spec().targetUrl(),spec().eventTypes(),List.of(Uuid7.generate())))).isInstanceOf(BusinessException.class);
        owner.update("UPDATE sys_account SET status='DISABLED' WHERE id=?",account);assertThatThrownBy(()->create(Uuid7.generate())).isInstanceOf(BusinessException.class);owner.update("UPDATE sys_account SET status='ACTIVE' WHERE id=?",account);assertThat(rows("integ_webhook_subscription")).isEqualTo(1);
    }
    @Test void unsafeTargetsAndUnknownEventsDoNotCreateFacts(){for(String target:List.of("http://receiver.example.com","https://127.0.0.1/x","https://[::1]/x","https://u:p@receiver.example.com/x","https://receiver.example.com/x?secret=x","https://receiver.example.com/x#fragment","https://receiver.example.com:0/x"))assertThatThrownBy(()->service.create(tenant,project,account,Uuid7.generate(),new WebhookSubscriptionService.Spec("bad",target,spec().eventTypes(),List.of()))).isInstanceOf(BusinessException.class);assertThatThrownBy(()->service.create(tenant,project,account,Uuid7.generate(),new WebhookSubscriptionService.Spec("bad",spec().targetUrl(),List.of("unknown"),List.of()))).isInstanceOf(BusinessException.class);assertThat(rows("integ_webhook_operation")).isZero();}
    @Test void outerRollbackRemovesSubscriptionRevisionAndReceipt(){assertThatThrownBy(()->tx.execute(s->{create(Uuid7.generate());throw new IllegalStateException("rollback");})).isInstanceOf(IllegalStateException.class);for(String table:List.of("integ_webhook_subscription","integ_webhook_revision","integ_webhook_operation"))assertThat(rows(table)).isZero();}
    @Test void derivedKeysSeparateProjectSubscriptionAndGeneration(){UUID sub=Uuid7.generate(),generation=Uuid7.generate();byte[] first=signing.derive("a",tenant,project,sub,generation);assertThat(first).isNotEqualTo(signing.derive("a",tenant,Uuid7.generate(),sub,generation)).isNotEqualTo(signing.derive("a",tenant,project,Uuid7.generate(),generation)).isNotEqualTo(signing.derive("a",tenant,project,sub,Uuid7.generate()));assertThatThrownBy(()->new WebhookSigningKeys(json,true,"{}","a")).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->new WebhookSigningKeys(json,true,"{\"a\":\"secret-should-not-appear\"}","a")).hasMessage("公开Webhook签名配置无效");}
}
