package com.things.link.bootstrap.integration;

import com.things.link.integration.application.*;
import com.things.link.integration.domain.WebhookDeliveryRepository;
import com.things.link.project.application.*;
import com.things.link.shared.id.Uuid7;
import com.things.link.shared.message.PublicWebhookEvent;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import java.time.*;
import java.util.*;
import static org.assertj.core.api.Assertions.*;

class WebhookQuotaTests extends WebhookFixture {
    @Autowired WebhookEventAdmission admission;@Autowired WebhookDeliveryState state;
    @Autowired WebhookDailyUsageContributor contributor;@Autowired DailyUsageReconciliationService reconciliation;
    @Autowired ProjectDailyQuotaDecisionService quota;
    @Autowired com.things.link.alarm.application.AlarmNotificationDailyUsageContributor alarmUsage;
    @Autowired com.things.link.rule.infrastructure.persistence.RuleExecutionDailyUsageContributor ruleUsage;
    @Autowired io.micrometer.core.instrument.MeterRegistry meters;
    UUID policy,neighbor;
    @BeforeEach void quotaPolicy(){policy=Uuid7.generate();owner.update("INSERT INTO sys_quota_policy(id,code,notification_delivery_daily_limit) VALUES (?,?,10)",policy,"wh"+policy.toString().replace("-","").substring(0,20));owner.update("UPDATE sys_tenant SET quota_policy_id=? WHERE id=?",policy,tenant);}
    @AfterEach void removeQuota(){for(String table:List.of("rule_execution_log","rule_version","rule_message","alarm_notification_delivery","alarm_notification_binding","alarm_notification_recipient","alarm_notification_template","alarm_notification_group","alarm_event","alarm_instance","alarm_rule"))owner.update("DELETE FROM "+table+" WHERE project_id=?",project);if(neighbor!=null){owner.update("DELETE FROM sys_usage_counter_daily WHERE project_id=?",neighbor);owner.update("DELETE FROM sys_project WHERE id=?",neighbor);}owner.update("UPDATE sys_tenant SET quota_policy_id=(SELECT id FROM sys_quota_policy WHERE code='FREE') WHERE id=?",tenant);owner.update("DELETE FROM sys_quota_policy WHERE id=?",policy);}
    PublicWebhookEvent event(){Instant now=owner.queryForObject("SELECT clock_timestamp()",java.sql.Timestamp.class).toInstant();return new PublicWebhookEvent(Uuid7.generate(),"device.online",tenant,project,0,"device",device,device,now,now,null,"{}");}
    void usage(UUID scope,long count){owner.update("DELETE FROM sys_usage_counter_daily WHERE project_id=? AND metric='NOTIFICATION_DELIVERY'",scope);owner.update("INSERT INTO sys_usage_counter_daily(id,tenant_id,project_id,usage_date,metric,used_value) VALUES (?,?,?,(clock_timestamp() AT TIME ZONE 'UTC')::date,'NOTIFICATION_DELIVERY',?)",Uuid7.generate(),tenant,scope,count);}
    long bill(){assertThat(owner.queryForList("SELECT metric,usage_date,used_value FROM sys_usage_counter_daily WHERE project_id=?",project)).as("DB now=%s JVM=%s deliveries=%s",owner.queryForObject("SELECT clock_timestamp()",String.class),Instant.now(),owner.queryForList("SELECT created_at FROM integ_webhook_delivery WHERE project_id=?",project)).isNotEmpty();return owner.queryForObject("SELECT used_value FROM sys_usage_counter_daily WHERE project_id=? AND metric='NOTIFICATION_DELIVERY' AND usage_date=(clock_timestamp() AT TIME ZONE 'UTC')::date",Long.class,project);}
    @Test void hardThresholdRemainsSoftButDegradedIsDurableAndNeverBackfilled(){create(Uuid7.generate());for(long count:List.of(0L,8L,10L)){usage(project,count);assertThat(admission.accept(event())).isEqualTo("ACCEPTED");}usage(project,12);var rejected=event();assertThat(admission.accept(rejected)).isEqualTo("QUOTA_DEGRADED");assertThat(rows("integ_webhook_delivery")).isEqualTo(3);usage(project,0);assertThat(admission.accept(rejected)).isEqualTo("DUPLICATE");assertThat(rows("integ_webhook_delivery")).isEqualTo(3);assertThat(owner.queryForObject("SELECT event_text IS NULL FROM integ_webhook_event WHERE event_id=?",Boolean.class,rejected.eventId())).isTrue();}
    @Test void zeroQuotaDisablesNewIntentsBeforeAnyUsageExists(){create(Uuid7.generate());owner.update("UPDATE sys_quota_policy SET notification_delivery_daily_limit=0 WHERE id=?",policy);assertThat(quota.decisionTrustedProject(tenant,project,QuotaMetric.NOTIFICATION_DELIVERY).disabled()).isTrue();assertThat(admission.accept(event())).isEqualTo("QUOTA_DEGRADED");assertThat(rows("integ_webhook_delivery")).isZero();owner.update("UPDATE sys_quota_policy SET notification_delivery_daily_limit=NULL WHERE id=?",policy);assertThat(admission.accept(event())).isEqualTo("ACCEPTED");}
    @Test void anotherProjectConsumesSameTenantPool(){create(Uuid7.generate());neighbor=Uuid7.generate();owner.update("INSERT INTO sys_project(id,tenant_id,name,project_key) VALUES (?,?,'neighbor',?)",neighbor,tenant,"wh"+neighbor.toString().replace("-",""));usage(neighbor,12);assertThat(quota.decideTrustedProject(tenant,project,QuotaMetric.NOTIFICATION_DELIVERY)).isEqualTo(QuotaStatus.DEGRADED);assertThat(admission.accept(event())).isEqualTo("QUOTA_DEGRADED");assertThat(rows("integ_webhook_delivery")).isZero();}
    @Test void noAudienceHasNoDeliveryOrQuotaConsumption(){usage(project,12);assertThat(admission.accept(event())).isEqualTo("ACCEPTED");assertThat(rows("integ_webhook_delivery")).isZero();assertThat(tx.<Long>execute(s->{rls.establish(tenant,project);return contributor.calculate(new DailyUsageScope(tenant,project),LocalDate.now(ZoneOffset.UTC)).getFirst().usedValue();})).isZero();}
    @Test void notificationAndWebhookFactsMergeAndAttemptsNeverDoubleBill(){create(Uuid7.generate());admission.accept(event());alarmDelivery();assertThat(rows("integ_webhook_delivery")).isEqualTo(1);assertThat(tx.<Long>execute(s->{rls.establish(tenant,project);return contributor.calculate(new DailyUsageScope(tenant,project),LocalDate.now(ZoneOffset.UTC)).getFirst().usedValue();})).as("UTC delivery contribution").isEqualTo(1);var scope=new DailyUsageScope(tenant,project);reconciliation.reconcile(scope);assertThat(bill()).isEqualTo(2);var c=new WebhookDeliveryRepository.Candidate(tenant,project,owner.queryForObject("SELECT id FROM integ_webhook_delivery WHERE project_id=?",UUID.class,project));var first=state.claim(c,true).orElseThrow();assertThat(state.finish(c,first.token(),WebhookDeliveryState.Outcome.RETRYABLE,503,1)).isTrue();owner.update("UPDATE integ_webhook_delivery SET next_attempt_at=clock_timestamp()-interval '1 second' WHERE id=?",c.id());var second=state.claim(c,true).orElseThrow();assertThat(state.finish(c,second.token(),WebhookDeliveryState.Outcome.SUCCEEDED,204,1)).isTrue();reconciliation.reconcile(scope);assertThat(bill()).isEqualTo(2);assertThat(rows("integ_webhook_attempt")).isEqualTo(2);}
    @Test void unavailableQuotaFunctionRollsBackAdmissionInsteadOfAcknowledging(){create(Uuid7.generate());owner.execute("REVOKE EXECUTE ON FUNCTION trusted_project_daily_quota_decision(uuid,uuid,date,varchar) FROM thingslink_app");try{assertThatThrownBy(()->admission.accept(event())).isInstanceOf(DataAccessException.class);assertThat(rows("integ_webhook_event")).isZero();assertThat(rows("integ_webhook_delivery")).isZero();assertThat(rows("integ_webhook_ingress_state")).isZero();}finally{owner.execute("GRANT EXECUTE ON FUNCTION trusted_project_daily_quota_decision(uuid,uuid,date,varchar) TO thingslink_app");}assertThat(admission.accept(event())).isEqualTo("ACCEPTED");}
    @Test void contributionIsUtcScopedDualRlsAndRollbackSafe(){create(Uuid7.generate());assertThatThrownBy(()->tx.execute(s->{admission.accept(event());throw new IllegalStateException("rollback");})).isInstanceOf(IllegalStateException.class);assertThat(rows("integ_webhook_delivery")).isZero();admission.accept(event());for(var scope:List.of(new DailyUsageScope(UUID.randomUUID(),project),new DailyUsageScope(tenant,UUID.randomUUID()))){assertThat(tx.<Long>execute(s->{rls.establish(scope.tenantId(),scope.projectId());return contributor.calculate(scope,LocalDate.now(ZoneOffset.UTC)).getFirst().usedValue();})).isZero();}assertThat(tx.<Long>execute(s->{rls.establish(tenant,project);return contributor.calculate(new DailyUsageScope(tenant,project),LocalDate.now(ZoneOffset.UTC).minusDays(1)).getFirst().usedValue();})).isZero();}
    @Test void degradationMetricUsesOnlyCommittedFixedLabels(){create(Uuid7.generate());usage(project,12);var counter=meters.get(WebhookAdmissionMetrics.NAME).tag("result","QUOTA_DEGRADED").counter();double before=counter.count();assertThatThrownBy(()->tx.execute(s->{assertThat(admission.accept(event())).isEqualTo("QUOTA_DEGRADED");throw new IllegalStateException("rollback");})).isInstanceOf(IllegalStateException.class);assertThat(counter.count()).isEqualTo(before);assertThat(admission.accept(event())).isEqualTo("QUOTA_DEGRADED");assertThat(counter.count()).isEqualTo(before+1);assertThat(counter.getId().getTags()).allMatch(t->Set.of("result","application").contains(t.getKey()));}
    @Test void allAffectedDailyContributorsUseUtcBoundariesRegardlessOfDatabaseTimeZone(){
        UUID subscription=create(Uuid7.generate()).subscription().id();UUID rule=Uuid7.generate(),version=Uuid7.generate();
        owner.update("INSERT INTO rule_message(id,tenant_id,project_id,name,created_by,created_at,updated_at) VALUES (?,?,?,'UTC',?,now(),now())",rule,tenant,project,account);
        owner.update("INSERT INTO rule_version(id,tenant_id,project_id,rule_id,version_number,source,source_sha256,created_by,created_at) VALUES (?,?,?,?,1,'input => input',repeat('a',64),?,now())",version,tenant,project,rule,account);
        LocalDate day=LocalDate.of(2026,1,2);Instant start=day.atStartOfDay(ZoneOffset.UTC).toInstant();
        for(Instant at:List.of(start.minusSeconds(1),start,start.plusSeconds(86399),start.plusSeconds(86400))){
            alarmDelivery(at);UUID id=Uuid7.generate();var timestamp=java.sql.Timestamp.from(at);
            owner.update("INSERT INTO integ_webhook_event VALUES (?,?,'device.online',?,0,repeat('a',64),?,?,?,'ACCEPTED','{}')",tenant,project,id,timestamp,timestamp,timestamp);
            owner.update("INSERT INTO integ_webhook_delivery(id,tenant_id,project_id,event_type,event_id,subscription_id,subscription_revision,created_at,deadline_at,status,next_attempt_at) VALUES (?,?,?,'device.online',?,?,1,?,?,'READY',?)",Uuid7.generate(),tenant,project,id,subscription,timestamp,java.sql.Timestamp.from(at.plusSeconds(86400)),timestamp);
            owner.update("INSERT INTO rule_execution_log(id,tenant_id,project_id,message_id,rule_id,rule_version_id,attempt,status,result_code,duration_millis,input_bytes,output_bytes,created_at) VALUES (?,?,?,?,?,?,1,'SUCCESS','SUCCESS',7,1,1,?)",Uuid7.generate(),tenant,project,Uuid7.generate(),rule,version,timestamp);
        }
        for(String zone:List.of("UTC","America/Los_Angeles","Asia/Shanghai"))tx.execute(s->{rls.establish(tenant,project);jdbc.queryForObject("SELECT set_config('TimeZone',?,true)",String.class,zone);var scope=new DailyUsageScope(tenant,project);
            assertThat(contributor.calculate(scope,day).getFirst().usedValue()).as("Webhook UTC window in %s",zone).isEqualTo(2);
            assertThat(alarmUsage.calculate(scope,day).getFirst().usedValue()).as("Alarm UTC window in %s",zone).isEqualTo(2);
            var values=ruleUsage.calculate(scope,day);assertThat(values.getFirst().usedValue()).as("Rule UTC window in %s",zone).isEqualTo(2);assertThat(values.get(1).usedValue()).isEqualTo(14);return null;});
    }
    void alarmDelivery(){alarmDelivery(Instant.now());}
    void alarmDelivery(Instant createdAt){UUID rule=Uuid7.generate(),instance=Uuid7.generate(),event=Uuid7.generate(),group=Uuid7.generate(),recipient=Uuid7.generate(),template=Uuid7.generate(),binding=Uuid7.generate();
        owner.update("INSERT INTO alarm_rule(id,tenant_id,project_id,name,alarm_type,originator_id,property_key,trigger_operator,trigger_threshold,clear_operator,clear_threshold,severity) VALUES (?,?,?,?,?,?,'value','GT',30,'LT',25,'WARNING')",rule,tenant,project,"quota"+rule,"TYPE"+rule,device);
        owner.update("INSERT INTO alarm_instance(id,tenant_id,project_id,rule_id,originator_type,originator_id,alarm_type,severity,condition_state,ack_state,first_condition_at,activated_at,last_received_at,last_value) VALUES (?,?,?,?,'DEVICE',?,?,'WARNING','ACTIVE','UNACKNOWLEDGED',now(),now(),now(),31)",instance,tenant,project,rule,device,"TYPE"+rule);
        owner.update("INSERT INTO alarm_event(id,tenant_id,project_id,instance_id,event_type,source_message_id,trace_id,received_at,condition_state,ack_state) VALUES (?,?,?,?,'ACTIVATED',?,'quota',now(),'ACTIVE','UNACKNOWLEDGED')",event,tenant,project,instance,Uuid7.generate());
        owner.update("INSERT INTO alarm_notification_group(id,tenant_id,project_id,name) VALUES (?,?,?,?)",group,tenant,project,"quota"+group);
        owner.update("INSERT INTO alarm_notification_recipient(id,tenant_id,project_id,group_id,channel,target) VALUES (?,?,?,?,'WEBHOOK','https://receiver.example.com')",recipient,tenant,project,group);
        owner.update("INSERT INTO alarm_notification_template(id,tenant_id,project_id,name,channel,body_template) VALUES (?,?,?,?,'WEBHOOK','body')",template,tenant,project,"quota"+template);
        owner.update("INSERT INTO alarm_notification_binding(id,tenant_id,project_id,rule_id,group_id,template_id,channel) VALUES (?,?,?,?,?,?,'WEBHOOK')",binding,tenant,project,rule,group,template);
        owner.update("INSERT INTO alarm_notification_delivery(id,tenant_id,project_id,instance_id,alarm_event_id,binding_id,recipient_id,channel,target_snapshot,body_snapshot,template_version,status,terminal_at,created_at) VALUES (?,?,?,?,?,?,?,'WEBHOOK','https://receiver.example.com','body',0,'SUCCEEDED',now(),?)",Uuid7.generate(),tenant,project,instance,event,binding,recipient,java.sql.Timestamp.from(createdAt));
    }
}
