package com.things.link.bootstrap.integration;
import com.things.link.integration.infrastructure.WebhookRetentionMaintenance;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.ApplicationContext;
import static org.assertj.core.api.Assertions.*;
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"things-link.integration.api-key.enabled=true","things-link.integration.webhook.enabled=false"})
class WebhookDisabledMaintenanceTests extends OpenDeviceHttpFixture {
    @Autowired WebhookRetentionMaintenance maintenance;@Autowired ApplicationContext context;
    @Autowired com.things.link.support.webhook.PublicWebhookSourceWriter source;
    @Autowired org.springframework.kafka.config.KafkaListenerEndpointRegistry listeners;
    @Test void disabledSourceWritesNothingAndHasNoListener(){assertThat(source.enabled()).isFalse();tx.execute(s->{source.append(null);return null;});assertThat(context.containsBean("webhookSourceKafkaConsumer")).isFalse();assertThat(listeners.getListenerContainer("public-webhook-source")).isNull();assertThat(owner.queryForObject("SELECT count(*) FROM sys_outbox_event WHERE project_id=? AND event_type='PUBLIC_WEBHOOK_SOURCE'",Integer.class,project)).isZero();}
    @AfterEach void removeMaintenanceFacts(){new org.springframework.transaction.support.TransactionTemplate(new org.springframework.jdbc.datasource.DataSourceTransactionManager(owner.getDataSource())).execute(s->{owner.queryForList("SELECT id FROM sys_project WHERE id=? FOR UPDATE",project);for(String table:java.util.List.of("integ_webhook_attempt","integ_webhook_delivery","integ_webhook_event","integ_webhook_ingress_state","integ_webhook_revision","integ_webhook_subscription"))owner.update("DELETE FROM "+table+" WHERE project_id=?",project);return null;});}
    @Test void disabledFeatureStillPurgesExistingFactsWithoutSenderWorker(){assertThat(context.containsBean("webhookDeliveryWorker")).isFalse();assertThat(context.containsBean("webhookRetentionMaintenance")).isTrue();owner.update("INSERT INTO integ_webhook_event VALUES (?,?,'device.online',gen_random_uuid(),0,repeat('a',64),clock_timestamp()-interval '8 days',clock_timestamp()-interval '8 days',clock_timestamp()-interval '8 days','STALE',NULL)",tenant,project);maintenance.tick();assertThat(owner.queryForObject("SELECT count(*) FROM integ_webhook_event WHERE project_id=?",Integer.class,project)).isZero();assertThat(owner.queryForObject("SELECT count(*) FROM integ_webhook_ingress_state WHERE project_id=?",Integer.class,project)).isEqualTo(1);}
    @Test void disabledFeatureStillTerminatesExpiredExistingDelivery(){java.util.UUID sub=java.util.UUID.randomUUID(),event=java.util.UUID.randomUUID();
        new org.springframework.transaction.support.TransactionTemplate(new org.springframework.jdbc.datasource.DataSourceTransactionManager(owner.getDataSource())).execute(s->{owner.update("INSERT INTO integ_webhook_subscription VALUES (?,?,?,0,?,clock_timestamp()-interval '10 days',1,'ACTIVE',clock_timestamp()-interval '10 days')",sub,tenant,project,account);owner.update("INSERT INTO integ_webhook_revision VALUES (?,?,?,1,'old','https://receiver.example.com',ARRAY['device.online'],ARRAY[]::uuid[],?,clock_timestamp()-interval '10 days','a',gen_random_uuid())",tenant,project,sub,account);return null;});
        owner.update("INSERT INTO integ_webhook_event VALUES (?,?,'device.online',?,0,repeat('a',64),clock_timestamp()-interval '10 days',clock_timestamp()-interval '10 days',clock_timestamp()-interval '10 days','ACCEPTED','{}')",tenant,project,event);
        owner.update("INSERT INTO integ_webhook_delivery(id,tenant_id,project_id,event_type,event_id,subscription_id,subscription_revision,created_at,deadline_at,status,next_attempt_at) VALUES (gen_random_uuid(),?,?,'device.online',?,?,1,clock_timestamp()-interval '10 days',clock_timestamp()-interval '9 days','READY',clock_timestamp()-interval '10 days')",tenant,project,event,sub);
        maintenance.tick();assertThat(owner.queryForObject("SELECT status FROM integ_webhook_delivery WHERE project_id=?",String.class,project)).isEqualTo("DEAD");assertThat(owner.queryForObject("SELECT count(*) FROM integ_webhook_attempt WHERE project_id=?",Integer.class,project)).isZero();assertThat(owner.queryForObject("SELECT count(*) FROM integ_webhook_event WHERE project_id=?",Integer.class,project)).isEqualTo(1);assertThat(context.containsBean("webhookDeliveryWorker")).isFalse();
    }
}
