package com.things.link.bootstrap.integration;

import com.things.link.integration.application.*;
import com.things.link.integration.domain.*;
import com.things.link.shared.error.*;
import com.things.link.shared.id.Uuid7;
import com.things.link.shared.message.PublicWebhookEvent;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.*;

class WebhookRecoveryTests extends WebhookFixture {
    @Autowired WebhookRecoveryService recovery;
    @Autowired WebhookEventAdmission admission;
    @Autowired WebhookDeliveryState state;
    @Autowired WebhookDeliveryRepository deliveries;
    Instant now(){return owner.queryForObject("SELECT clock_timestamp()",java.sql.Timestamp.class).toInstant();}
    WebhookDeliveryRepository.Candidate enqueue(){var time=now();var id=Uuid7.generate();admission.accept(new PublicWebhookEvent(id,"device.online",tenant,project,0,"device",device,device,time,time,null,"{}"));return new WebhookDeliveryRepository.Candidate(tenant,project,owner.queryForObject("SELECT id FROM integ_webhook_delivery WHERE project_id=? AND event_id=?",UUID.class,project,id));}
    WebhookDeliveryRepository.Delivery read(WebhookDeliveryRepository.Candidate c){return tx.execute(s->{rls.establish(tenant,project);return deliveries.find(c.id()).orElseThrow();});}
    void fail(WebhookDeliveryRepository.Candidate c){var d=state.claim(c,true).orElseThrow();state.finish(c,d.token(),WebhookDeliveryState.Outcome.PERMANENT,400,1);}
    void age(WebhookDeliveryRepository.Candidate c,String interval){owner.execute("ALTER TABLE integ_webhook_delivery DISABLE TRIGGER integ_webhook_delivery_guard");try{owner.update("UPDATE integ_webhook_delivery SET terminal_at=clock_timestamp()-?::interval WHERE id=?",interval,c.id());}finally{owner.execute("ALTER TABLE integ_webhook_delivery ENABLE TRIGGER integ_webhook_delivery_guard");}}
    WebhookRecoveryService.Result recover(WebhookDeliveryRepository.Candidate c,UUID op,int round){return recovery.recover(tenant,project,account,op,c.id(),round);}
    UUID admin(){UUID actor=Uuid7.generate();additionalAccounts.add(actor);owner.update("INSERT INTO sys_account(id,email,password_hash,display_name) VALUES (?,?,'unused','recovery')",actor,actor+"@example.com");owner.update("INSERT INTO sys_project_member(id,project_id,account_id,role) VALUES (?,?,?,'ADMIN')",Uuid7.generate(),project,actor);return actor;}
    @Test void recoveryKeepsOriginalIdentityBodyAttemptsAndAuditIsAtomic(){create(Uuid7.generate());var c=enqueue();fail(c);var before=read(c);String body=owner.queryForObject("SELECT event_text FROM integ_webhook_event WHERE event_id=?",String.class,before.eventId());UUID op=Uuid7.generate();Instant started=now();var result=recover(c,op,1);var after=read(c);assertThat(result.resultRound()).isEqualTo(2);assertThat(result.replayed()).isFalse();assertThat(after.attempts()).isEqualTo(1);assertThat(after.roundAttempts()).isZero();assertThat(after.id()).isEqualTo(c.id());assertThat(after.revision()).isEqualTo(before.revision());assertThat(after.eventId()).isEqualTo(before.eventId());assertThat(after.deadlineAt()).isBetween(started.plus(Duration.ofDays(1)),now().plus(Duration.ofDays(1)));assertThat(after.terminalAt()).isNull();assertThat(owner.queryForObject("SELECT event_text FROM integ_webhook_event WHERE event_id=?",String.class,before.eventId())).isEqualTo(body);assertThat(rows("integ_webhook_delivery")).isEqualTo(1);assertThat(rows("integ_webhook_recovery_operation")).isEqualTo(1);assertThat(owner.queryForObject("SELECT count(*) FROM sys_audit_log WHERE project_id=? AND action='integration.webhook.recover' AND target_id=?",Integer.class,project,c.id())).isEqualTo(1);assertThat(state.claim(c,true).orElseThrow().attempts()).isEqualTo(2);}
    @Test void sameOperationReplayDoesNotConsumeAnotherRoundAndConflictsReject(){create(Uuid7.generate());var c=enqueue();fail(c);UUID op=Uuid7.generate();var first=recover(c,op,1);fail(c);assertThat(recover(c,op,1).replayed()).isTrue();assertThat(read(c).round()).isEqualTo(2);assertThat(recovery.operation(tenant,project,account,op).completedAt()).isEqualTo(first.completedAt());assertThatThrownBy(()->recover(c,op,2)).isInstanceOf(BusinessException.class);UUID other=admin();assertThatThrownBy(()->recovery.recover(tenant,project,other,op,c.id(),1)).isInstanceOf(BusinessException.class);assertThatThrownBy(()->recovery.operation(tenant,project,other,op)).isInstanceOf(BusinessException.class);assertThat(rows("integ_webhook_recovery_operation")).isEqualTo(1);}
    @Test void concurrentIdenticalOperationHasOneTransition()throws Exception{create(Uuid7.generate());var c=enqueue();fail(c);UUID op=Uuid7.generate();try(var pool=Executors.newVirtualThreadPerTaskExecutor()){var gate=new CountDownLatch(1);var pending=new ArrayList<Future<WebhookRecoveryService.Result>>();for(int i=0;i<8;i++)pending.add(pool.submit(()->{gate.await();return recover(c,op,1);}));gate.countDown();int fresh=0;for(var f:pending)if(!f.get(15,TimeUnit.SECONDS).replayed())fresh++;assertThat(fresh).isEqualTo(1);}assertThat(read(c).round()).isEqualTo(2);assertThat(rows("integ_webhook_recovery_operation")).isEqualTo(1);}
    @Test void concurrentDistinctOperationsUseExpectedRoundCas()throws Exception{create(Uuid7.generate());var c=enqueue();fail(c);try(var pool=Executors.newVirtualThreadPerTaskExecutor()){var gate=new CountDownLatch(1);var pending=new ArrayList<Future<Boolean>>();for(int i=0;i<8;i++)pending.add(pool.submit(()->{gate.await();try{recover(c,Uuid7.generate(),1);return true;}catch(BusinessException conflict){assertThat(conflict.errorCode()).isEqualTo(CommonErrorCode.RESOURCE_STATE_CONFLICT);return false;}}));gate.countDown();int fresh=0;for(var f:pending)if(f.get(15,TimeUnit.SECONDS))fresh++;assertThat(fresh).isEqualTo(1);}assertThat(rows("integ_webhook_recovery_operation")).isEqualTo(1);}
    @Test void threeRoundsFifteenAttemptsIsAnAbsoluteBound(){create(Uuid7.generate());var c=enqueue();for(int round=1;round<=3;round++){for(int attempt=1;attempt<=5;attempt++){var d=state.claim(c,true).orElseThrow();assertThat(d.attempts()).isEqualTo((round-1)*5+attempt);state.finish(c,d.token(),WebhookDeliveryState.Outcome.RETRYABLE,503,1);if(attempt<5)owner.update("UPDATE integ_webhook_delivery SET next_attempt_at=clock_timestamp()-interval '1 second' WHERE id=?",c.id());}assertThat(read(c).status()).isEqualTo("DEAD");if(round<3)recover(c,Uuid7.generate(),round);}assertThatThrownBy(()->recover(c,Uuid7.generate(),3)).isInstanceOf(BusinessException.class);assertThat(read(c).attempts()).isEqualTo(15);assertThat(rows("integ_webhook_attempt")).isEqualTo(15);assertThat(rows("integ_webhook_recovery_operation")).isEqualTo(2);assertThat(state.claim(c,true)).isEmpty();}
    @Test void sevenDayWindowExcludesBoundaryAndIncludesRecentTerminal(){create(Uuid7.generate());var c=enqueue();fail(c);age(c,"7 days");assertThatThrownBy(()->recover(c,Uuid7.generate(),1)).isInstanceOf(BusinessException.class);age(c,"6 days 23 hours");assertThat(recover(c,Uuid7.generate(),1).resultRound()).isEqualTo(2);}
    @Test void oldRevisionAndOriginalAuthorRevocationAreNotBypassedByAnotherAdmin(){var sub=create(Uuid7.generate()).subscription();var c=enqueue();fail(c);UUID actor=admin();owner.update("UPDATE sys_account SET status='DISABLED' WHERE id=?",account);assertThatThrownBy(()->recovery.recover(tenant,project,actor,Uuid7.generate(),c.id(),1)).isInstanceOf(BusinessException.class);owner.update("UPDATE sys_account SET status='ACTIVE' WHERE id=?",account);change(sub.id(),1,"ROTATE");assertThatThrownBy(()->recovery.recover(tenant,project,actor,Uuid7.generate(),c.id(),1)).isInstanceOf(BusinessException.class);assertThat(read(c).status()).isEqualTo("DEAD");assertThat(rows("integ_webhook_recovery_operation")).isZero();}
    @Test void currentManagerWrongScopeAndGenerationAreRechecked(){create(Uuid7.generate());var c=enqueue();fail(c);UUID actor=admin();owner.update("UPDATE sys_project_member SET role='VIEWER' WHERE project_id=? AND account_id=?",project,actor);assertThatThrownBy(()->recovery.recover(tenant,project,actor,Uuid7.generate(),c.id(),1)).isInstanceOf(BusinessException.class);assertThatThrownBy(()->recovery.recover(UUID.randomUUID(),project,account,Uuid7.generate(),c.id(),1)).isInstanceOf(BusinessException.class);owner.update("UPDATE sys_project SET lifecycle_generation=lifecycle_generation+1 WHERE id=?",project);assertThatThrownBy(()->recover(c,Uuid7.generate(),1)).isInstanceOf(BusinessException.class);assertThat(rows("integ_webhook_recovery_operation")).isZero();}
    @Test void succeededCancelledAndReadyNeverRevive(){create(Uuid7.generate());for(String terminal:List.of("READY","SUCCEEDED","CANCELLED")){var c=enqueue();if(!terminal.equals("READY")){var d=state.claim(c,true).orElseThrow();if(terminal.equals("SUCCEEDED"))state.finish(c,d.token(),WebhookDeliveryState.Outcome.SUCCEEDED,200,1);else state.cancel(c,d.token(),"TEST");}assertThatThrownBy(()->recover(c,Uuid7.generate(),1)).isInstanceOf(BusinessException.class);assertThat(read(c).status()).isEqualTo(terminal);}assertThat(rows("integ_webhook_recovery_operation")).isZero();}
    @Test void auditFailureRollsBackRoundReceiptAndBudget(){create(Uuid7.generate());var c=enqueue();fail(c);owner.execute("REVOKE INSERT ON sys_audit_log FROM thingslink_app");try{assertThatThrownBy(()->recover(c,Uuid7.generate(),1)).isInstanceOf(DataAccessException.class);}finally{owner.execute("GRANT INSERT ON sys_audit_log TO thingslink_app");}assertThat(read(c).status()).isEqualTo("DEAD");assertThat(read(c).round()).isEqualTo(1);assertThat(rows("integ_webhook_recovery_operation")).isZero();assertThat(rows("integ_webhook_attempt")).isEqualTo(1);}
    @Test void operationReceiptSurvivesRemovedDeliveryAndRemainsIsolatedImmutable(){create(Uuid7.generate());var c=enqueue();fail(c);UUID op=Uuid7.generate();recover(c,op,1);fail(c);owner.update("DELETE FROM integ_webhook_attempt WHERE delivery_id=?",c.id());owner.update("DELETE FROM integ_webhook_delivery WHERE id=?",c.id());assertThat(recovery.operation(tenant,project,account,op).current()).isNull();assertThat(recover(c,op,1).replayed()).isTrue();assertThat(rows("integ_webhook_delivery")).isZero();for(UUID wrong:List.of(UUID.randomUUID(),tenant)){assertThat(tx.<Integer>execute(s->{rls.establish(wrong,wrong.equals(tenant)?UUID.randomUUID():project);return jdbc.queryForObject("SELECT count(*) FROM integ_webhook_recovery_operation",Integer.class);})).isZero();}assertThatThrownBy(()->tx.execute(s->{rls.establish(tenant,project);return jdbc.update("DELETE FROM integ_webhook_recovery_operation");})).isInstanceOf(DataAccessException.class);assertThatThrownBy(()->owner.update("UPDATE integ_webhook_recovery_operation SET result_round=3 WHERE operation_id=?",op)).isInstanceOf(DataAccessException.class);}
    @Test void pendingCapacityRejectsRecoveryWithoutPartialFacts(){var sub=create(Uuid7.generate()).subscription();var c=enqueue();fail(c);owner.update("INSERT INTO integ_webhook_event SELECT ?,?,'device.online',gen_random_uuid(),0,repeat('a',64),clock_timestamp(),clock_timestamp(),clock_timestamp(),'ACCEPTED','{}' FROM generate_series(1,10000)",tenant,project);owner.update("INSERT INTO integ_webhook_delivery(id,tenant_id,project_id,event_type,event_id,subscription_id,subscription_revision,created_at,deadline_at,status,next_attempt_at) SELECT gen_random_uuid(),tenant_id,project_id,event_type,event_id,?,1,clock_timestamp(),clock_timestamp()+interval '24 hours','READY',clock_timestamp() FROM integ_webhook_event WHERE project_id=? AND event_id<>?",sub.id(),project,read(c).eventId());assertThatThrownBy(()->recover(c,Uuid7.generate(),1)).isInstanceOfSatisfying(BusinessException.class,e->assertThat(e.errorCode()).isEqualTo(CommonErrorCode.TOO_MANY_REQUESTS));assertThat(read(c).status()).isEqualTo("DEAD");assertThat(rows("integ_webhook_recovery_operation")).isZero();}
}
