package com.things.link.bootstrap.integration;

import com.things.link.integration.application.*;
import com.things.link.integration.domain.*;
import com.things.link.integration.infrastructure.WebhookRetentionMaintenance;
import com.things.link.shared.id.Uuid7;
import com.things.link.shared.message.PublicWebhookEvent;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.*;

class WebhookRetentionTests extends WebhookFixture {
    @Autowired WebhookRetentionService retention;@Autowired WebhookRetentionMaintenance maintenance;
    @Autowired WebhookDeliveryState state;@Autowired WebhookEventAdmission admission;@Autowired WebhookEventCodec codec;
    @Autowired WebhookRecoveryService recovery;
    final List<UUID> deletingProjects=new ArrayList<>();
    @AfterEach void cleanDeletingProjects(){for(UUID id:deletingProjects){owner.update("DELETE FROM integ_webhook_event WHERE project_id=?",id);owner.update("DELETE FROM sys_project WHERE id=?",id);}}
    @Test void deletingProjectsCannotFillCandidateBatch(){for(int i=0;i<25;i++){UUID id=Uuid7.generate();deletingProjects.add(id);owner.update("INSERT INTO sys_project(id,tenant_id,name,project_key,status,deleted_at) VALUES (?,?,'deleting',?,'DELETING',clock_timestamp())",id,tenant,"wh"+id.toString().replace("-",""));owner.update("INSERT INTO integ_webhook_event VALUES (?,?,'device.online',gen_random_uuid(),0,repeat('a',64),clock_timestamp()-interval '20 days',clock_timestamp()-interval '20 days',clock_timestamp()-interval '20 days','STALE',NULL)",tenant,id);}events(1);assertThat(retention.candidates()).containsExactly(scope());}
    WebhookRetentionRepository.Scope scope(){return new WebhookRetentionRepository.Scope(tenant,project);}
    Instant now(){return owner.queryForObject("SELECT clock_timestamp()",java.sql.Timestamp.class).toInstant();}
    void events(int count){owner.update("INSERT INTO integ_webhook_event SELECT ?,?,'device.online',gen_random_uuid(),0,repeat('a',64),clock_timestamp()-interval '10 days',clock_timestamp()-interval '10 days',clock_timestamp()-interval '10 days','ACCEPTED','{}' FROM generate_series(1,?)",tenant,project,count);}
    WebhookDeliveryRepository.Candidate delivery(UUID sub){UUID event=owner.queryForObject("SELECT event_id FROM integ_webhook_event WHERE project_id=? ORDER BY event_id LIMIT 1",UUID.class,project),id=Uuid7.generate();owner.update("INSERT INTO integ_webhook_delivery(id,tenant_id,project_id,event_type,event_id,subscription_id,subscription_revision,created_at,deadline_at,status,next_attempt_at) VALUES (?,?,?,'device.online',?,?,1,clock_timestamp()-interval '10 days',clock_timestamp()-interval '9 days','READY',clock_timestamp()-interval '10 days')",id,tenant,project,event,sub);return new WebhookDeliveryRepository.Candidate(tenant,project,id);}
    void terminalAge(WebhookDeliveryRepository.Candidate c,String age){owner.execute("ALTER TABLE integ_webhook_delivery DISABLE TRIGGER integ_webhook_delivery_guard");try{owner.update("UPDATE integ_webhook_delivery SET terminal_at=clock_timestamp()-?::interval WHERE id=?",age,c.id());}finally{owner.execute("ALTER TABLE integ_webhook_delivery ENABLE TRIGGER integ_webhook_delivery_guard");}}
    @Test void fiveHundredBudgetIncludesFloorAndPersistsReplayBarrier(){events(501);assertThat(retention.purge(scope(),500)).isEqualTo(500);assertThat(rows("integ_webhook_event")).isEqualTo(2);assertThat(rows("integ_webhook_ingress_state")).isEqualTo(1);assertThat(retention.purge(scope(),500)).isEqualTo(3);assertThat(rows("integ_webhook_event")).isZero();assertThat(rows("integ_webhook_ingress_state")).isEqualTo(1);}
    @Test void acceptedAgeAloneCannotPurgeSourceStillAboveFloor(){
        var time=now();var e=new PublicWebhookEvent(Uuid7.generate(),"device.online",tenant,project,0,"device",device,device,time.minus(Duration.ofDays(7)).plusSeconds(240),time.minus(Duration.ofDays(7)).plusSeconds(240),null,"{}");var encoded=codec.encode(e);
        owner.update("INSERT INTO integ_webhook_event VALUES (?,?,'device.online',?,0,?,?,?,?,'ACCEPTED',?)",tenant,project,e.eventId(),encoded.hash(),java.sql.Timestamp.from(e.recordedAt()),java.sql.Timestamp.from(e.occurredAt()),java.sql.Timestamp.from(time.minus(Duration.ofDays(7)).minusSeconds(60)),encoded.eventText());
        assertThat(retention.purge(scope(),500)).isEqualTo(1);assertThat(rows("integ_webhook_event")).isEqualTo(1);assertThat(retention.candidates()).doesNotContain(scope());
        owner.update("UPDATE integ_webhook_ingress_state SET reject_before=? WHERE project_id=?",java.sql.Timestamp.from(e.recordedAt().plusSeconds(60)),project);var floor=owner.queryForObject("SELECT reject_before FROM integ_webhook_ingress_state WHERE project_id=?",java.sql.Timestamp.class,project);
        assertThat(retention.candidates()).contains(scope());assertThat(retention.purge(scope(),500)).isEqualTo(2);assertThat(owner.queryForObject("SELECT reject_before FROM integ_webhook_ingress_state WHERE project_id=?",java.sql.Timestamp.class,project)).isEqualTo(floor);create(Uuid7.generate());assertThat(admission.accept(e)).isEqualTo("STALE");assertThat(rows("integ_webhook_delivery")).isZero();
    }
    @Test void recoveryAndRecentTerminalProtectOldBodyAndAttempts(){var sub=create(Uuid7.generate()).subscription();events(1);var c=delivery(sub.id());state.claim(c,false);assertThat(retention.purge(scope(),500)).isEqualTo(1);assertThat(rows("integ_webhook_event")).isEqualTo(1);recovery.recover(tenant,project,account,Uuid7.generate(),c.id(),1);var claim=state.claim(c,true).orElseThrow();assertThat(retention.purge(scope(),500)).isEqualTo(1);assertThat(rows("integ_webhook_attempt")).isEqualTo(1);state.finish(c,claim.token(),WebhookDeliveryState.Outcome.PERMANENT,400,1);terminalAge(c,"7 days");assertThat(retention.purge(scope(),500)).isEqualTo(1);assertThat(retention.candidates()).doesNotContain(scope());
        owner.execute("ALTER TABLE integ_webhook_attempt DISABLE TRIGGER integ_webhook_attempt_guard");try{owner.update("UPDATE integ_webhook_attempt SET started_at=clock_timestamp()-interval '8 days',finished_at=clock_timestamp()-interval '7 days' WHERE delivery_id=?",c.id());}finally{owner.execute("ALTER TABLE integ_webhook_attempt ENABLE TRIGGER integ_webhook_attempt_guard");}
        assertThat(retention.purge(scope(),500)).isEqualTo(4);assertThat(rows("integ_webhook_attempt")).isZero();assertThat(rows("integ_webhook_delivery")).isZero();assertThat(rows("integ_webhook_event")).isZero();assertThat(rows("integ_webhook_recovery_operation")).isEqualTo(1);}
    @Test void conflictOwnAgeProtectsOriginalReceipt(){events(1);owner.update("INSERT INTO integ_webhook_conflict SELECT tenant_id,project_id,event_type,event_id,repeat('b',64),clock_timestamp() FROM integ_webhook_event WHERE project_id=?",project);assertThat(retention.purge(scope(),500)).isEqualTo(1);assertThat(rows("integ_webhook_event")).isEqualTo(1);owner.update("INSERT INTO integ_webhook_conflict SELECT tenant_id,project_id,event_type,event_id,repeat('c',64),clock_timestamp()-interval '8 days' FROM integ_webhook_event WHERE project_id=?",project);assertThat(retention.purge(scope(),500)).isEqualTo(2);assertThat(rows("integ_webhook_conflict")).isEqualTo(1);assertThat(rows("integ_webhook_event")).isEqualTo(1);}
    @Test void outerRollbackRestoresPayloadAndFloor(){events(3);assertThatThrownBy(()->tx.execute(s->{assertThat(retention.purge(scope(),500)).isEqualTo(4);throw new IllegalStateException("rollback");})).isInstanceOf(IllegalStateException.class);assertThat(rows("integ_webhook_event")).isEqualTo(3);assertThat(rows("integ_webhook_ingress_state")).isZero();}
    @Test void scopeMismatchAndOrdinaryDeleteAreRejected(){events(1);assertThat(retention.purge(new WebhookRetentionRepository.Scope(UUID.randomUUID(),project),500)).isZero();assertThatThrownBy(()->tx.execute(s->{rls.establish(UUID.randomUUID(),project);return jdbc.queryForObject("SELECT integ_webhook_purge_scope(?,?,500)",Integer.class,tenant,project);})).isInstanceOf(DataAccessException.class);assertThatThrownBy(()->tx.execute(s->{rls.establish(tenant,project);return jdbc.update("DELETE FROM integ_webhook_event");})).isInstanceOf(DataAccessException.class);assertThat(rows("integ_webhook_event")).isEqualTo(1);}
    @Test void wholeMaintenanceRoundStaysWithinFiveHundred(){var sub=create(Uuid7.generate()).subscription();events(601);owner.update("INSERT INTO integ_webhook_delivery(id,tenant_id,project_id,event_type,event_id,subscription_id,subscription_revision,created_at,deadline_at,status,next_attempt_at) SELECT gen_random_uuid(),tenant_id,project_id,event_type,event_id,?,1,clock_timestamp()-interval '10 days',clock_timestamp()-interval '9 days','READY',clock_timestamp()-interval '10 days' FROM integ_webhook_event WHERE project_id=? ORDER BY event_id LIMIT 100",sub.id(),project);maintenance.tick();int terminal=owner.queryForObject("SELECT count(*) FROM integ_webhook_delivery WHERE project_id=? AND status='DEAD'",Integer.class,project);int removed=601-rows("integ_webhook_event");assertThat(terminal).isEqualTo(100);assertThat(removed).isEqualTo(299);assertThat(terminal+removed+rows("integ_webhook_ingress_state")).isLessThanOrEqualTo(500);assertThat(rows("integ_webhook_attempt")).isZero();}
    @Test void currentRevisionIsProtectedButOldRevisionAndRevokedPairAgeOut(){
        UUID sub=Uuid7.generate();new org.springframework.transaction.support.TransactionTemplate(new org.springframework.jdbc.datasource.DataSourceTransactionManager(owner.getDataSource())).execute(s->{owner.update("INSERT INTO integ_webhook_subscription VALUES (?,?,?,0,?,clock_timestamp()-interval '10 days',1,'ACTIVE',clock_timestamp()-interval '10 days')",sub,tenant,project,account);owner.update("INSERT INTO integ_webhook_revision VALUES (?,?,?,1,'retention','https://receiver.example.com',ARRAY['device.online'],ARRAY[]::uuid[],?,clock_timestamp()-interval '10 days','a',gen_random_uuid())",tenant,project,sub,account);return null;});
        assertThat(retention.purge(scope(),500)).isEqualTo(1);assertThat(rows("integ_webhook_revision")).isEqualTo(1);change(sub,1,"REVOKE");assertThat(retention.purge(scope(),500)).isEqualTo(2);assertThat(rows("integ_webhook_subscription")).isEqualTo(1);assertThat(rows("integ_webhook_revision")).isEqualTo(1);
        owner.execute("ALTER TABLE integ_webhook_subscription DISABLE TRIGGER integ_webhook_subscription_guard");try{owner.update("UPDATE integ_webhook_subscription SET updated_at=clock_timestamp()-interval '7 days' WHERE id=?",sub);}finally{owner.execute("ALTER TABLE integ_webhook_subscription ENABLE TRIGGER integ_webhook_subscription_guard");}
        assertThat(retention.purge(scope(),2)).isEqualTo(1);assertThat(rows("integ_webhook_subscription")).isEqualTo(1);assertThat(retention.purge(scope(),3)).isEqualTo(3);assertThat(rows("integ_webhook_subscription")).isZero();assertThat(rows("integ_webhook_revision")).isZero();assertThat(rows("integ_webhook_operation")).isEqualTo(1);
    }
    @Test void projectManagementLockSerializesPurgeWithRecovery()throws Exception{var sub=create(Uuid7.generate()).subscription();events(1);var c=delivery(sub.id());state.claim(c,false);
        try(var connection=java.sql.DriverManager.getConnection(POSTGRES.getJdbcUrl(),POSTGRES.getUsername(),POSTGRES.getPassword());var pool=Executors.newVirtualThreadPerTaskExecutor()){connection.setAutoCommit(false);try(var sql=connection.prepareStatement("SELECT id FROM sys_project WHERE id=? FOR UPDATE")){sql.setObject(1,project);sql.executeQuery().close();}var purge=pool.submit(()->retention.purge(scope(),500));try{org.awaitility.Awaitility.await().atMost(Duration.ofSeconds(2)).until(()->owner.queryForObject("SELECT count(*) FROM pg_stat_activity WHERE datname=current_database() AND wait_event_type='Lock'",Integer.class)>0);assertThat(purge.isDone()).isFalse();}finally{connection.commit();}assertThat(purge.get(10,TimeUnit.SECONDS)).isEqualTo(1);}
        assertThat(recovery.recover(tenant,project,account,Uuid7.generate(),c.id(),1).resultRound()).isEqualTo(2);
    }
}
