package com.things.link.bootstrap.integration;

import com.things.link.device.application.*;
import com.things.link.shared.message.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.TestPropertySource;
import tools.jackson.databind.ObjectMapper;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.*;
import static com.things.link.device.application.DeviceAccessSessionPort.ActivityResult.*;

/** Window/Outbox transactions are real; deterministic tests call expiry directly, not an automatic-timer claim. */
@TestPropertySource(properties="things-link.device.activity-expiry.enabled=false")
class WebhookActivitySourceTests extends WebhookFixture {
    @Autowired DeviceAccessSessionPort sessions;
    @Autowired DeviceAccessActivityService activity;
    @Autowired ObjectMapper mapper;
    @BeforeEach void bind(){owner.update("INSERT INTO dev_access_binding(device_id,tenant_id,project_id,protocol) VALUES(?,?,?,'HTTP')",device,tenant,project);}
    @AfterEach void cleanup(){owner.update("DELETE FROM dev_access_binding WHERE project_id=?",project);owner.update("DELETE FROM sys_outbox_event WHERE project_id=?",project);}
    DeviceAccessSessionPort.ActivityResult record(TransportProtocol protocol){return sessions.recordActivity(tenant,project,device,protocol);}
    boolean expire(){return activity.expire(tenant,project,device);}
    boolean online(){return owner.queryForObject("SELECT activity_online FROM dev_access_binding WHERE device_id=?",Boolean.class,device);}
    Instant last(){return owner.queryForObject("SELECT last_activity_at FROM dev_access_binding WHERE device_id=?",Timestamp.class,device).toInstant();}
    Instant age(){owner.update("UPDATE dev_access_binding SET last_activity_at=clock_timestamp()-interval '301 seconds' WHERE device_id=?",device);return last();}
    List<PublicWebhookSource> sources(){return owner.queryForList("SELECT payload FROM sys_outbox_event WHERE project_id=? AND event_type='PUBLIC_WEBHOOK_SOURCE' ORDER BY created_at,id",String.class,project).stream().map(s->mapper.readValue(s,PublicWebhookSource.class)).sorted(Comparator.comparingLong(s->Long.parseLong(mapper.readTree(s.eventText()).path("payload").path("presenceRevision").asString()))).toList();}
    @Test void activityRefreshAndPersistentExpiryUseIndependentProtocolFact(){String mqtt=owner.queryForObject("SELECT status FROM dev_device WHERE id=?",String.class,device);assertThat(record(TransportProtocol.HTTP)).isEqualTo(ACCEPTED);assertThat(record(TransportProtocol.HTTP)).isEqualTo(ACCEPTED);assertThat(sources()).hasSize(1);assertThat(expire()).isFalse();Instant previous=age();assertThat(expire()).isTrue();assertThat(expire()).isFalse();assertThat(online()).isFalse();var events=sources();assertThat(events).hasSize(2);assertThat(events.getLast().event().occurredAt()).isEqualTo(previous.plusSeconds(300));assertThat(mapper.readTree(events.getLast().eventText()).path("payload").path("reason").asString()).isEqualTo("ACTIVITY_EXPIRED");assertThat(owner.queryForObject("SELECT status FROM dev_device WHERE id=?",String.class,device)).isEqualTo(mqtt);}
    @Test void requestAfterUnscannedExpiryRecordsOfflineThenOnline(){record(TransportProtocol.HTTP);Instant previous=age();assertThat(record(TransportProtocol.HTTP)).isEqualTo(ACCEPTED);var events=sources();assertThat(events.stream().map(s->s.event().eventType())).containsExactly("device.online","device.offline","device.online");assertThat(events.get(1).event().occurredAt()).isEqualTo(previous.plusSeconds(300));assertThat(online()).isTrue();assertThat(expire()).isFalse();}
    @Test void coapCarriesProtocolWithoutInventedMessageIdentity(){owner.update("UPDATE dev_access_binding SET protocol='COAP',config_version=config_version+1 WHERE device_id=?",device);assertThat(record(TransportProtocol.COAP)).isEqualTo(ACCEPTED);var event=sources().getFirst();var body=mapper.readTree(event.eventText()).path("payload");assertThat(body.path("source").asString()).isEqualTo("COAP");assertThat(body.path("from").asString()).isEqualTo("INACTIVE");assertThat(body.path("sourceMessageId").isNull()).isTrue();assertThat(event.event().traceId()).isNull();}
    @Test void clockRollbackNeverShortensActivityWindow(){record(TransportProtocol.HTTP);owner.update("UPDATE dev_access_binding SET last_activity_at=clock_timestamp()+interval '60 seconds' WHERE device_id=?",device);Instant future=last();assertThat(record(TransportProtocol.HTTP)).isEqualTo(ACCEPTED);assertThat(last()).isEqualTo(future);assertThat(expire()).isFalse();assertThat(sources()).hasSize(1);}
    @Test void wrongDisabledDeletedAndArchivedCannotRecordActivity(){assertThat(record(TransportProtocol.COAP)).isEqualTo(PLANE_NOT_ENABLED);owner.update("UPDATE dev_access_binding SET enabled=false,config_version=config_version+1 WHERE device_id=?",device);assertThat(record(TransportProtocol.HTTP)).isEqualTo(PLANE_NOT_ENABLED);owner.update("UPDATE dev_access_binding SET enabled=true,config_version=config_version+1 WHERE device_id=?",device);owner.update("UPDATE dev_device SET deleted_at=now() WHERE id=?",device);assertThat(record(TransportProtocol.HTTP)).isEqualTo(PLANE_NOT_ENABLED);owner.update("UPDATE dev_device SET deleted_at=null WHERE id=?",device);owner.update("UPDATE sys_project SET status='ARCHIVED' WHERE id=?",project);assertThat(record(TransportProtocol.HTTP)).isEqualTo(PROJECT_UNAVAILABLE);assertThat(sources()).isEmpty();assertThat(online()).isFalse();}
    @Test void archivedWindowStillExpiresWithoutNewPublicEvent(){record(TransportProtocol.HTTP);age();owner.update("UPDATE sys_project SET status='ARCHIVED' WHERE id=?",project);assertThat(expire()).isTrue();assertThat(online()).isFalse();assertThat(sources()).hasSize(1);}
    @Test void enclosingRollbackRestoresWindowSequenceAndOutbox(){tx.execute(s->{assertThat(record(TransportProtocol.HTTP)).isEqualTo(ACCEPTED);s.setRollbackOnly();return null;});assertThat(online()).isFalse();assertThat(sources()).isEmpty();assertThat(owner.queryForObject("SELECT webhook_presence_revision FROM dev_device WHERE id=?",Long.class,device)).isZero();}
    @Test void sourceFailureRollsBackActivityAndExpiryAndRetryRetainsOneEdge(){owner.execute("REVOKE INSERT ON sys_outbox_event FROM thingslink_app");try{assertThatThrownBy(()->record(TransportProtocol.HTTP)).isInstanceOf(org.springframework.dao.DataAccessException.class);}finally{owner.execute("GRANT INSERT ON sys_outbox_event TO thingslink_app");}assertThat(online()).isFalse();assertThat(sources()).isEmpty();record(TransportProtocol.HTTP);age();owner.execute("REVOKE INSERT ON sys_outbox_event FROM thingslink_app");try{assertThatThrownBy(this::expire).isInstanceOf(org.springframework.dao.DataAccessException.class);}finally{owner.execute("GRANT INSERT ON sys_outbox_event TO thingslink_app");}assertThat(online()).isTrue();assertThat(sources()).hasSize(1);assertThat(expire()).isTrue();assertThat(sources()).hasSize(2);}
    @Test void concurrentRefreshAndScansDoNotDuplicateEdges()throws Exception{try(var pool=Executors.newVirtualThreadPerTaskExecutor()){var first=new ArrayList<Future<?>>();for(int i=0;i<8;i++)first.add(pool.submit(()->record(TransportProtocol.HTTP)));for(var f:first)f.get(15,TimeUnit.SECONDS);assertThat(sources()).hasSize(1);age();var race=new ArrayList<Future<?>>();for(int i=0;i<8;i++){race.add(pool.submit(this::expire));race.add(pool.submit(()->record(TransportProtocol.HTTP)));}for(var f:race)f.get(15,TimeUnit.SECONDS);}assertThat(sources().stream().map(s->s.event().eventType())).containsExactly("device.online","device.offline","device.online");assertThat(online()).isTrue();}
    @Test void crossTenantOrProjectCannotMutateWindow(){assertThat(sessions.recordActivity(UUID.randomUUID(),project,device,TransportProtocol.HTTP)).isEqualTo(PROJECT_UNAVAILABLE);assertThat(sessions.recordActivity(tenant,UUID.randomUUID(),device,TransportProtocol.HTTP)).isNotEqualTo(ACCEPTED);assertThat(sources()).isEmpty();assertThat(online()).isFalse();}
    @Test void tcpAuthenticationActivityDoesNotPretendToBeAConnectedSession(){owner.update("UPDATE dev_access_binding SET protocol='TCP',config_version=config_version+1 WHERE device_id=?",device);assertThat(record(TransportProtocol.TCP)).isEqualTo(ACCEPTED);assertThat(last()).isNotNull();assertThat(online()).isFalse();assertThat(sources()).isEmpty();}
    @Test void candidateFunctionIsBoundedAndExposesOnlyLocators(){record(TransportProtocol.HTTP);age();
        for(int i=0;i<103;i++){UUID id=UUID.randomUUID();insertDevice(id,null);owner.update("INSERT INTO dev_access_binding(device_id,tenant_id,project_id,protocol,last_activity_at,activity_online) VALUES(?,?,?,'HTTP',clock_timestamp()-interval '301 seconds',true)",id,tenant,project);}
        assertThat(jdbc.queryForList("SELECT * FROM dev_activity_expiry_candidates(-1)")).isEmpty();
        assertThat(jdbc.queryForList("SELECT * FROM dev_activity_expiry_candidates(100000)")).hasSize(100);
        assertThat(jdbc.queryForList("SELECT * FROM dev_activity_expiry_candidates(100000)")).allSatisfy(row->assertThat(row.keySet()).containsExactlyInAnyOrder("tenant_id","project_id","device_id")).hasSizeLessThanOrEqualTo(100);assertThat(owner.queryForObject("SELECT count(*) FROM pg_proc p,LATERAL aclexplode(p.proacl) a WHERE p.proname='dev_activity_expiry_candidates' AND a.grantee=0",Integer.class)).isZero();}
    @Test void wrongTenantExpiryCannotClearWindowEvenWhenProjectIdMatches(){record(TransportProtocol.HTTP);age();assertThat(activity.expire(UUID.randomUUID(),project,device)).isFalse();assertThat(online()).isTrue();assertThat(sources()).hasSize(1);assertThat(expire()).isTrue();}
}
