package com.things.link.bootstrap.integration;
import com.things.link.device.infrastructure.emqx.EmqxConnectionEventService;
import com.things.link.shared.message.PublicWebhookSource;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import tools.jackson.databind.ObjectMapper;
import java.util.*;
import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.*;
class WebhookMqttSourceTests extends WebhookFixture {
    @Autowired EmqxConnectionEventService connections;
    @Autowired ObjectMapper mapper;
    @Autowired io.micrometer.core.instrument.MeterRegistry meters;
    @org.springframework.beans.factory.annotation.Value("${things-link.security.broker-callback.secret}") String brokerSecret;
    String username;
    @BeforeEach void offline(){owner.update("UPDATE dev_device SET status='OFFLINE' WHERE id=?",device);username=owner.queryForObject("SELECT project_key FROM sys_project WHERE id=?",String.class,project)+"/"+owner.queryForObject("SELECT device_key FROM dev_device WHERE id=?",String.class,device);}
    @AfterEach void cleanupConnections(){owner.update("DELETE FROM dev_connection WHERE project_id=?",project);owner.update("DELETE FROM sys_outbox_event WHERE project_id=?",project);}
    boolean connect(String id){return mqttConnected(connections,username,id,"127.0.0.1","test-node",mqttIdentity(device));}
    boolean disconnect(String id){return mqttDisconnected(connections,username,id,"remote arbitrary reason",mqttIdentity(device));}
    List<PublicWebhookSource> sources(){return owner.queryForList("SELECT payload FROM sys_outbox_event WHERE project_id=? AND event_type='PUBLIC_WEBHOOK_SOURCE' ORDER BY created_at,id",String.class,project).stream().map(s->mapper.readValue(s,PublicWebhookSource.class)).toList();}
    long revision(){return owner.queryForObject("SELECT webhook_presence_revision FROM dev_device WHERE id=?",Long.class,device);}
    @Test void protectedRealHttpCallbackCreatesSourceOnlyWithBrokerCredential()throws Exception{
        String body=mapper.writeValueAsString(mqttBody(Map.of("username",username,"clientid","http-client","peerhost","127.0.0.1","node","test-node")));
        var denied=request("POST","/api/v1/emqx/events/connected",body,null,Map.of());assertThat(denied.statusCode()).isIn(401,403);assertThat(sources()).isEmpty();
        var accepted=request("POST","/api/v1/emqx/events/connected",body,null,Map.of("X-Broker-Callback-Token",brokerSecret));assertThat(accepted.statusCode()).isEqualTo(200);assertThat(sources()).hasSize(1);
        var disconnected=request("POST","/api/v1/emqx/events/disconnected",mapper.writeValueAsString(mqttBody(Map.of("username",username,"clientid","http-client","reason","normal"))),null,Map.of("X-Broker-Callback-Token",brokerSecret));assertThat(disconnected.statusCode()).isEqualTo(200);assertThat(sources()).hasSize(2);
    }
    @Test void firstAndLastConnectionGenerateOnlyActualEdges(){assertThat(connect("a")).isTrue();assertThat(connect("a")).isTrue();assertThat(connect("b")).isTrue();assertThat(sources()).hasSize(1);assertThat(disconnect("a")).isTrue();assertThat(sources()).hasSize(1);assertThat(disconnect("b")).isTrue();assertThat(disconnect("b")).isTrue();var facts=sources();assertThat(facts).hasSize(2);assertThat(facts.stream().map(s->s.event().eventType())).containsExactly("device.online","device.offline");assertThat(revision()).isEqualTo(2);var online=mapper.readTree(facts.getFirst().eventText()).get("payload");var offline=mapper.readTree(facts.getLast().eventText()).get("payload");assertThat(online.path("presenceRevision").asString()).isEqualTo("1");assertThat(offline.path("presenceRevision").asString()).isEqualTo("2");assertThat(offline.path("reason").asString()).isEqualTo("DISCONNECTED");assertThat(offline.toString()).doesNotContain("arbitrary","127.0.0.1");assertThat(online.path("sourceMessageId").isNull()).isTrue();}
    @Test void concurrentFirstAndLastConnectionsAreSerialized()throws Exception{try(var pool=Executors.newVirtualThreadPerTaskExecutor()){var gate=new CountDownLatch(1);var tasks=new ArrayList<Future<Boolean>>();for(int i=0;i<8;i++){String id="c"+i;tasks.add(pool.submit(()->{gate.await();return connect(id);}));}gate.countDown();for(var task:tasks)assertThat(task.get(20,TimeUnit.SECONDS)).isTrue();assertThat(sources()).hasSize(1);tasks.clear();for(int i=0;i<8;i++){String id="c"+i;tasks.add(pool.submit(()->disconnect(id)));}for(var task:tasks)assertThat(task.get(20,TimeUnit.SECONDS)).isTrue();}assertThat(sources()).hasSize(2);assertThat(revision()).isEqualTo(2);assertThat(owner.queryForObject("SELECT status FROM dev_device WHERE id=?",String.class,device)).isEqualTo("OFFLINE");}
    @Test void enclosingTransactionRollbackRemovesStateEdgeAndSequence(){double before=meters.get("thingslink.device.connection.events").tag("event","connected").counter().count();tx.execute(s->{assertThat(connect("rolled")).isTrue();s.setRollbackOnly();return null;});assertThat(sources()).isEmpty();assertThat(revision()).isZero();assertThat(owner.queryForObject("SELECT count(*) FROM dev_connection WHERE device_id=?",Integer.class,device)).isZero();assertThat(owner.queryForObject("SELECT status FROM dev_device WHERE id=?",String.class,device)).isEqualTo("OFFLINE");assertThat(meters.get("thingslink.device.connection.events").tag("event","connected").counter().count()).isEqualTo(before);}
    @Test void sourceWriteFailureMakesCallbackFailAndRollsBackConnection(){owner.execute("REVOKE INSERT ON sys_outbox_event FROM thingslink_app");try{assertThatThrownBy(()->connect("failed")).isInstanceOf(org.springframework.dao.DataAccessException.class);}finally{owner.execute("GRANT INSERT ON sys_outbox_event TO thingslink_app");}assertThat(sources()).isEmpty();assertThat(revision()).isZero();assertThat(owner.queryForObject("SELECT count(*) FROM dev_connection WHERE device_id=?",Integer.class,device)).isZero();}
    @Test void inactiveProjectCanCloseConnectionWithoutCreatingNewPublicSource(){assertThat(connect("archived")).isTrue();owner.update("UPDATE sys_project SET status='ARCHIVED' WHERE id=?",project);assertThat(disconnect("archived")).isTrue();assertThat(sources()).hasSize(1);assertThat(revision()).isEqualTo(1);assertThat(owner.queryForObject("SELECT status FROM dev_device WHERE id=?",String.class,device)).isEqualTo("OFFLINE");}
    @Test void generationIsFrozenAndSequenceCannotRegress(){owner.update("UPDATE sys_project SET lifecycle_generation=3 WHERE id=?",project);assertThat(connect("generation")).isTrue();assertThat(sources().getFirst().event().projectGeneration()).isEqualTo(3);assertThatThrownBy(()->owner.update("UPDATE dev_device SET webhook_presence_revision=0 WHERE id=?",device)).isInstanceOf(org.springframework.dao.DataAccessException.class);assertThatThrownBy(()->owner.update("UPDATE dev_device SET webhook_presence_revision=3 WHERE id=?",device)).isInstanceOf(org.springframework.dao.DataAccessException.class);}
    @Test void initialInactiveOfflineIsNotInventedAsAConnectivityEdge(){owner.update("UPDATE dev_device SET status='INACTIVE' WHERE id=?",device);assertThat(disconnect("missing")).isFalse();assertThat(sources()).isEmpty();assertThat(connect("first")).isTrue();assertThat(mapper.readTree(sources().getFirst().eventText()).path("payload").path("from").asString()).isEqualTo("INACTIVE");}
    @Test void projectChangeWaitsForTheOriginalCallbackCommit()throws Exception{var entered=new CountDownLatch(1);var release=new CountDownLatch(1);try(var pool=Executors.newVirtualThreadPerTaskExecutor()){var callback=pool.submit(()->tx.execute(s->{assertThat(connect("locked")).isTrue();entered.countDown();try{assertThat(release.await(15,TimeUnit.SECONDS)).isTrue();}catch(InterruptedException e){throw new RuntimeException(e);}return true;}));assertThat(entered.await(10,TimeUnit.SECONDS)).isTrue();var started=new CountDownLatch(1);var archive=pool.submit(()->{started.countDown();return owner.update("UPDATE sys_project SET status='ARCHIVED' WHERE id=?",project);});assertThat(started.await(5,TimeUnit.SECONDS)).isTrue();try{assertThatThrownBy(()->archive.get(300,TimeUnit.MILLISECONDS)).isInstanceOf(TimeoutException.class);}finally{release.countDown();}assertThat(callback.get(10,TimeUnit.SECONDS)).isTrue();assertThat(archive.get(10,TimeUnit.SECONDS)).isEqualTo(1);}assertThat(sources()).hasSize(1);}
}
