package com.things.link.bootstrap.integration;
import com.things.link.device.application.*;
import com.things.link.shared.message.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.TestPropertySource;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.*;

/** Real session and source transactions. Physical TLS and process death are qualified separately. */
@TestPropertySource(properties="things-link.device.tcp-expiry.enabled=false")
class WebhookTcpSourceTests extends WebhookFixture {
    @Autowired DeviceAccessSessionPort sessions;
    @Autowired DeviceTcpSessionService tcp;
    @BeforeEach void bind(){owner.update("INSERT INTO dev_access_binding(device_id,tenant_id,project_id,protocol,heartbeat_seconds) VALUES(?,?,?,'TCP',300)",device,tenant,project);}
    @AfterEach void cleanupTcp(){for(String table:List.of("dev_connection","dev_access_binding","sys_outbox_event"))owner.update("DELETE FROM "+table+" WHERE project_id=?",project);}
    DeviceAccessSessionPort.EstablishmentRequest request(String owner){return new DeviceAccessSessionPort.EstablishmentRequest(tenant,project,device,TransportProtocol.TCP,"session-"+owner,owner,"127.0.0.1",10_000L);}
    DeviceAccessSessionPort.Established connect(String owner){return ((DeviceAccessSessionPort.Establishment.Allowed)sessions.establish(request(owner))).established();}
    boolean expire(){return tcp.expire(tenant,project,device);}
    List<PublicWebhookSource> sources(){return owner.queryForList("SELECT payload FROM sys_outbox_event WHERE project_id=? AND event_type='PUBLIC_WEBHOOK_SOURCE' ORDER BY created_at,id",String.class,project).stream().map(s->json.readValue(s,PublicWebhookSource.class)).sorted(Comparator.comparingLong(s->Long.parseLong(json.readTree(s.eventText()).path("payload").path("presenceRevision").asString()))).toList();}
    Instant age(){owner.update("UPDATE dev_connection SET last_seen_at=clock_timestamp()-interval '31 seconds' WHERE device_id=? AND disconnected_at IS NULL",device);return owner.queryForObject("SELECT last_seen_at FROM dev_connection WHERE device_id=? AND disconnected_at IS NULL",Timestamp.class,device).toInstant();}
    String reason(UUID row){return owner.queryForObject("SELECT disconnect_reason FROM dev_connection WHERE id=?",String.class,row);}
    @Test void actualIntervalIsFrozenAndFirstLastEdgesFollowSessionNotDeviceStatus(){var first=connect("a");assertThat(owner.queryForObject("SELECT heartbeat_interval_millis FROM dev_connection WHERE id=?",Long.class,first.rowId())).isEqualTo(10_000);assertThat(sources()).hasSize(1);assertThat(json.readTree(sources().getFirst().eventText()).path("payload").path("from").asString()).isEqualTo("INACTIVE");assertThat(sessions.touch(tenant,project,device,first.rowId(),"a")).isTrue();assertThat(sources()).hasSize(1);assertThat(sessions.close(tenant,project,device,first.rowId(),"a","secret-like arbitrary reason")).isTrue();assertThat(sources()).hasSize(2);assertThat(sources().getLast().eventText()).doesNotContain("secret-like");assertThat(sessions.close(tenant,project,device,first.rowId(),"a","repeat")).isFalse();assertThatThrownBy(()->owner.update("UPDATE dev_connection SET heartbeat_interval_millis=20000 WHERE id=?",first.rowId())).isInstanceOf(org.springframework.dao.DataAccessException.class);}
    @Test void takeoverDoesNotInventOfflineAndOldOwnerCannotCloseReplacement(){var a=connect("a");var b=connect("b");assertThat(b.generation()).isEqualTo(a.generation()+1);assertThat(b.replacedPriorSession()).isTrue();assertThat(sources()).hasSize(1);assertThat(sessions.close(tenant,project,device,a.rowId(),"a","old")).isFalse();assertThat(sessions.touch(tenant,project,device,b.rowId(),"a")).isFalse();assertThat(sessions.active(tenant,project,device).orElseThrow().rowId()).isEqualTo(b.rowId());assertThat(sessions.close(tenant,project,device,b.rowId(),"b","normal")).isTrue();assertThat(sources()).hasSize(2);}
    @Test void expiryUsesActualThreeCyclesAndExpiredRowsAreUnroutableBeforeScan(){var a=connect("a");Instant last=age();assertThat(sessions.active(tenant,project,device)).isEmpty();assertThat(expire()).isTrue();assertThat(expire()).isFalse();assertThat(reason(a.rowId())).isEqualTo("heartbeat_timeout");assertThat(sources()).hasSize(2);assertThat(sources().getLast().event().occurredAt()).isEqualTo(last.plusSeconds(30));assertThat(json.readTree(sources().getLast().eventText()).path("payload").path("reason").asString()).isEqualTo("HEARTBEAT_EXPIRED");}
    @Test void lateHeartbeatCannotReviveExpiredSession(){var a=connect("a");age();assertThat(sessions.touch(tenant,project,device,a.rowId(),"a")).isFalse();assertThat(reason(a.rowId())).isEqualTo("heartbeat_timeout");assertThat(sources()).hasSize(2);}
    @Test void reconnectAfterUnscannedExpiryRecordsOfflineBeforeOnline(){connect("a");age();connect("b");assertThat(sources().stream().map(s->s.event().eventType())).containsExactly("device.online","device.offline","device.online");assertThat(expire()).isFalse();}
    @Test void clockRollbackCannotShortenHeartbeatDeadline(){var a=connect("a");owner.update("UPDATE dev_connection SET last_seen_at=clock_timestamp()+interval '60 seconds' WHERE id=?",a.rowId());Instant before=owner.queryForObject("SELECT last_seen_at FROM dev_connection WHERE id=?",Timestamp.class,a.rowId()).toInstant();assertThat(sessions.touch(tenant,project,device,a.rowId(),"a")).isTrue();assertThat(owner.queryForObject("SELECT last_seen_at FROM dev_connection WHERE id=?",Timestamp.class,a.rowId()).toInstant()).isEqualTo(before);assertThat(expire()).isFalse();}
    @Test void archivedProjectRejectsEstablishAndStillClosesWithoutPublicSource(){var a=connect("a");owner.update("UPDATE sys_project SET status='ARCHIVED' WHERE id=?",project);assertThat(sessions.establish(request("b"))).isEqualTo(new DeviceAccessSessionPort.Establishment.Rejected(DeviceAccessSessionPort.Rejection.PROJECT_UNAVAILABLE));assertThat(sessions.close(tenant,project,device,a.rowId(),"a","archived")).isTrue();assertThat(sources()).hasSize(1);}
    @Test void originalRollbackAndSourceFailureRestoreSessionAndRevision(){tx.execute(s->{connect("rolled");s.setRollbackOnly();return null;});assertThat(sources()).isEmpty();assertThat(owner.queryForObject("SELECT count(*) FROM dev_connection WHERE device_id=?",Integer.class,device)).isZero();owner.execute("REVOKE INSERT ON sys_outbox_event FROM thingslink_app");try{assertThatThrownBy(()->connect("failed")).isInstanceOf(org.springframework.dao.DataAccessException.class);}finally{owner.execute("GRANT INSERT ON sys_outbox_event TO thingslink_app");}assertThat(owner.queryForObject("SELECT count(*) FROM dev_connection WHERE device_id=?",Integer.class,device)).isZero();connect("accepted");age();owner.execute("REVOKE INSERT ON sys_outbox_event FROM thingslink_app");try{assertThatThrownBy(this::expire).isInstanceOf(org.springframework.dao.DataAccessException.class);}finally{owner.execute("GRANT INSERT ON sys_outbox_event TO thingslink_app");}assertThat(owner.queryForObject("SELECT count(*) FROM dev_connection WHERE device_id=? AND disconnected_at IS NULL",Integer.class,device)).isEqualTo(1);assertThat(sources()).hasSize(1);assertThat(expire()).isTrue();assertThat(sources()).hasSize(2);}
    @Test void concurrentTakeoversAndExpiryHaveOneEdgePerBoundary()throws Exception{try(var pool=Executors.newVirtualThreadPerTaskExecutor()){var jobs=new ArrayList<Future<?>>();for(int i=0;i<8;i++){String id="c"+i;jobs.add(pool.submit(()->connect(id)));}for(var job:jobs)job.get(15,TimeUnit.SECONDS);assertThat(sources()).hasSize(1);age();jobs.clear();for(int i=0;i<8;i++){String id="d"+i;jobs.add(pool.submit(this::expire));jobs.add(pool.submit(()->connect(id)));}for(var job:jobs)job.get(15,TimeUnit.SECONDS);}assertThat(sources().stream().map(s->s.event().eventType())).containsExactly("device.online","device.offline","device.online");}
    @Test void crossTenantCannotEstablishOrExpireAnotherSession(){var a=connect("a");age();assertThat(tcp.expire(UUID.randomUUID(),project,device)).isFalse();assertThat(sessions.close(UUID.randomUUID(),project,device,a.rowId(),"a","foreign")).isFalse();assertThat(sessions.touch(UUID.randomUUID(),project,device,a.rowId(),"a")).isFalse();assertThat(sessions.establish(new DeviceAccessSessionPort.EstablishmentRequest(UUID.randomUUID(),project,device,TransportProtocol.TCP,"wrong","wrong",null,10_000L))).isEqualTo(new DeviceAccessSessionPort.Establishment.Rejected(DeviceAccessSessionPort.Rejection.PROJECT_UNAVAILABLE));assertThat(sources()).hasSize(1);assertThat(expire()).isTrue();}
    @Test void candidatesAreBoundedAndOnlyExposeLocators(){
        for(int i=0;i<104;i++){UUID id=UUID.randomUUID();insertDevice(id,null);owner.update("INSERT INTO dev_connection(id,tenant_id,project_id,device_id,protocol,last_seen_at,heartbeat_interval_millis) VALUES(gen_random_uuid(),?,?,?,'TCP',clock_timestamp()-interval '31 seconds',10000)",tenant,project,id);}
        assertThat(jdbc.queryForList("SELECT * FROM dev_tcp_expiry_candidates(9999)")).hasSize(100).allSatisfy(row->assertThat(row.keySet()).containsExactlyInAnyOrder("tenant_id","project_id","device_id"));
        assertThat(jdbc.queryForList("SELECT * FROM dev_tcp_expiry_candidates(-1)")).isEmpty();
        assertThat(owner.queryForObject("SELECT count(*) FROM pg_proc p,LATERAL aclexplode(p.proacl) a WHERE p.proname='dev_tcp_expiry_candidates' AND a.grantee=0",Integer.class)).isZero();
    }
}
