package com.things.link.bootstrap.integration;

import com.things.link.integration.application.*;
import com.things.link.integration.domain.WebhookDeliveryRepository;
import com.things.link.shared.id.Uuid7;
import com.things.link.shared.message.PublicWebhookEvent;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.*;

/** Real PostgreSQL transactions, independent connections and owner-only clock fault injection. */
class WebhookEventDeliveryTests extends WebhookFixture {
    @Autowired WebhookEventAdmission admission;
    @Autowired WebhookDeliveryState state;
    @Autowired WebhookEventCodec codec;
    @Autowired WebhookDeliveryRepository deliveries;
    Instant now(){return owner.queryForObject("SELECT clock_timestamp()",java.sql.Timestamp.class).toInstant();}
    PublicWebhookEvent event(UUID id,Instant recorded,String payload){return new PublicWebhookEvent(id,"device.online",tenant,project,0,"device",device,device,recorded,recorded,"trace",payload);}
    PublicWebhookEvent event(){return event(Uuid7.generate(),now(),"{\"value\":1}");}
    WebhookDeliveryRepository.Candidate candidate(){return new WebhookDeliveryRepository.Candidate(tenant,project,owner.queryForObject("SELECT id FROM integ_webhook_delivery WHERE project_id=?",UUID.class,project));}
    WebhookDeliveryRepository.Delivery delivery(WebhookDeliveryRepository.Candidate c){return tx.execute(s->{rls.establish(tenant,project);return deliveries.find(c.id()).orElseThrow();});}
    void due(WebhookDeliveryRepository.Candidate c){owner.update("UPDATE integ_webhook_delivery SET next_attempt_at=clock_timestamp()-interval '1 second' WHERE id=?",c.id());}
    void expire(WebhookDeliveryRepository.Candidate c){owner.update("UPDATE integ_webhook_delivery SET lease_until=clock_timestamp()-interval '1 second' WHERE id=?",c.id());}
    @Test void originalTransactionRollbackRemovesEventPlanAndFloor(){create(Uuid7.generate());assertThatThrownBy(()->tx.execute(s->{assertThat(admission.accept(event())).isEqualTo("ACCEPTED");throw new IllegalStateException("source rollback");})).isInstanceOf(IllegalStateException.class);for(String table:List.of("integ_webhook_event","integ_webhook_delivery","integ_webhook_ingress_state"))assertThat(rows(table)).isZero();}
    @Test void duplicatesDoNotRefreezeNewAudienceAndConflictsPreserveOriginal(){var first=create(Uuid7.generate());var e=event();assertThat(admission.accept(e)).isEqualTo("ACCEPTED");create(Uuid7.generate());change(first.subscription().id(),1,"PAUSE");assertThat(admission.accept(e)).isEqualTo("DUPLICATE");assertThat(rows("integ_webhook_delivery")).isEqualTo(1);var conflict=event(e.eventId(),e.recordedAt(),"{\"value\":2}");assertThat(admission.accept(conflict)).isEqualTo("CONFLICT");assertThat(admission.accept(conflict)).isEqualTo("CONFLICT");assertThat(rows("integ_webhook_conflict")).isEqualTo(1);assertThat(delivery(candidate()).revision()).isEqualTo(1);assertThat(owner.queryForObject("SELECT event_text FROM integ_webhook_event WHERE project_id=?",String.class,project)).contains("\"value\":1");}
    @Test void concurrentSameSourceFreezesExactlyOnePlan()throws Exception{create(Uuid7.generate());var e=event();try(var pool=Executors.newVirtualThreadPerTaskExecutor()){var gate=new CountDownLatch(1);var futures=new ArrayList<Future<String>>();for(int n=0;n<12;n++)futures.add(pool.submit(()->{gate.await();return admission.accept(e);}));gate.countDown();var results=new ArrayList<String>();for(var f:futures)results.add(f.get(20,TimeUnit.SECONDS));assertThat(results.stream().filter("ACCEPTED"::equals).count()).isEqualTo(1);assertThat(results.stream().filter("DUPLICATE"::equals).count()).isEqualTo(11);}assertThat(rows("integ_webhook_delivery")).isEqualTo(1);}
    @Test void emptyMatchIsAlsoFrozenAndDeviceFiltersAreApplied(){create(Uuid7.generate());var e=event();var foreign=new PublicWebhookEvent(e.eventId(),e.eventType(),tenant,project,0,"device",Uuid7.generate(),Uuid7.generate(),e.occurredAt(),e.recordedAt(),null,"{}");assertThat(admission.accept(foreign)).isEqualTo("ACCEPTED");service.create(tenant,project,account,Uuid7.generate(),new WebhookSubscriptionService.Spec("all",spec().targetUrl(),spec().eventTypes(),List.of()));assertThat(admission.accept(foreign)).isEqualTo("DUPLICATE");assertThat(rows("integ_webhook_delivery")).isZero();assertThat(admission.accept(event())).isEqualTo("ACCEPTED");assertThat(rows("integ_webhook_delivery")).isEqualTo(2);}
    @Test void canonicalPrecisionAndCompleteWireSizeArePreserved(){create(Uuid7.generate());var e=event(Uuid7.generate(),now(),"{\"a\":9007199254740993,\"b\":0.123456789012345678901234567890}");assertThat(admission.accept(e)).isEqualTo("ACCEPTED");String body=owner.queryForObject("SELECT event_text FROM integ_webhook_event WHERE project_id=?",String.class,project);assertThat(body).contains("9007199254740993","0.12345678901234567890123456789");assertThat(admission.accept(event(e.eventId(),e.recordedAt(),"{\"b\":0.12345678901234567890123456789,\"a\":9007199254740993}"))).isEqualTo("DUPLICATE");assertThat(admission.accept(event(Uuid7.generate(),now(),"{\"text\":\""+"中".repeat(90000)+"\"}"))).isEqualTo("OVERSIZE");assertThat(admission.accept(event(Uuid7.generate(),now(),"{\"text\":\""+"x".repeat(262000)+"\"}"))).isEqualTo("OVERSIZE");assertThat(rows("integ_webhook_delivery")).isEqualTo(1);assertThat(owner.queryForObject("SELECT count(*) FROM integ_webhook_event WHERE project_id=? AND result='OVERSIZE' AND event_text IS NULL",Integer.class,project)).isEqualTo(2);}
    @Test void retainedFloorRejectsReplayAfterPurgeAndNeverRegresses(){var e=event(Uuid7.generate(),now().minus(Duration.ofDays(8)),"{}");assertThat(admission.accept(e)).isEqualTo("STALE");owner.update("DELETE FROM integ_webhook_event WHERE project_id=?",project);create(Uuid7.generate());assertThat(admission.accept(e)).isEqualTo("STALE");owner.update("UPDATE integ_webhook_ingress_state SET reject_before=clock_timestamp()+interval '1 day' WHERE project_id=?",project);var floor=owner.queryForObject("SELECT reject_before FROM integ_webhook_ingress_state WHERE project_id=?",java.sql.Timestamp.class,project);assertThat(admission.accept(event())).isEqualTo("STALE");assertThat(owner.queryForObject("SELECT reject_before FROM integ_webhook_ingress_state WHERE project_id=?",java.sql.Timestamp.class,project)).isEqualTo(floor);assertThatThrownBy(()->owner.update("UPDATE integ_webhook_ingress_state SET reject_before=clock_timestamp() WHERE project_id=?",project)).isInstanceOf(DataAccessException.class);assertThat(rows("integ_webhook_delivery")).isZero();}
    @Test void existingReceiptSurvivesClockRollbackWithoutRefreezing(){var e=event(Uuid7.generate(),now().plusSeconds(3600),"{}");var encoded=codec.encode(e);owner.update("INSERT INTO integ_webhook_event VALUES (?,?,'device.online',?,0,?,?,?,?,'ACCEPTED',?)",tenant,project,e.eventId(),encoded.hash(),java.sql.Timestamp.from(e.recordedAt()),java.sql.Timestamp.from(e.occurredAt()),java.sql.Timestamp.from(e.recordedAt()),encoded.eventText());create(Uuid7.generate());assertThat(admission.accept(e)).isEqualTo("DUPLICATE");assertThat(rows("integ_webhook_delivery")).isZero();}
    @Test void futureSourceTimeRollsBackAndWrongGenerationCreatesNothing(){assertThatThrownBy(()->admission.accept(event(Uuid7.generate(),now().plusSeconds(3600),"{}"))).isInstanceOf(IllegalStateException.class);var e=event();assertThat(admission.accept(new PublicWebhookEvent(e.eventId(),e.eventType(),tenant,project,1,"device",device,device,e.occurredAt(),e.recordedAt(),null,"{}"))).isEqualTo("OUT_OF_SCOPE");assertThat(rows("integ_webhook_event")).isZero();assertThat(rows("integ_webhook_ingress_state")).isZero();}
    @Test void concurrentClaimHasOneOwnerAndExpiredTokenCannotFinish()throws Exception{create(Uuid7.generate());admission.accept(event());var c=candidate();try(var pool=Executors.newVirtualThreadPerTaskExecutor()){var gate=new CountDownLatch(1);var futures=new ArrayList<Future<Boolean>>();for(int n=0;n<12;n++)futures.add(pool.submit(()->{gate.await();return state.claim(c,true).isPresent();}));gate.countDown();int claimed=0;for(var f:futures)if(f.get(20,TimeUnit.SECONDS))claimed++;assertThat(claimed).isEqualTo(1);}var old=delivery(c);expire(c);assertThat(state.finish(c,old.token(),WebhookDeliveryState.Outcome.SUCCEEDED,200,1)).isFalse();var next=state.claim(c,true).orElseThrow();assertThat(next.attempts()).isEqualTo(2);assertThat(next.token()).isNotEqualTo(old.token());assertThat(state.finish(c,old.token(),WebhookDeliveryState.Outcome.SUCCEEDED,200,1)).isFalse();assertThat(owner.queryForObject("SELECT result FROM integ_webhook_attempt WHERE delivery_id=? AND attempt_no=1",String.class,c.id())).isEqualTo("UNKNOWN");assertThat(state.finish(c,next.token(),WebhookDeliveryState.Outcome.SUCCEEDED,204,1)).isTrue();assertThat(delivery(c).status()).isEqualTo("SUCCEEDED");assertThat(state.claim(c,true)).isEmpty();}
    @Test void fifthOwnerDeathIsTerminalWithoutSixthAttempt(){create(Uuid7.generate());admission.accept(event());var c=candidate();for(int i=1;i<=5;i++){assertThat(state.claim(c,true).orElseThrow().attempts()).isEqualTo(i);expire(c);}assertThat(state.claim(c,true)).isEmpty();assertThat(delivery(c).status()).isEqualTo("DEAD");assertThat(rows("integ_webhook_attempt")).isEqualTo(5);assertThat(owner.queryForObject("SELECT count(*) FROM integ_webhook_attempt WHERE project_id=? AND result='UNKNOWN'",Integer.class,project)).isEqualTo(5);}
    @Test void retryBackoffsAreBoundedAndFifthFailureDies(){create(Uuid7.generate());admission.accept(event());var c=candidate();for(int i=1;i<=5;i++){var d=state.claim(c,true).orElseThrow();Instant before=now();assertThat(state.finish(c,d.token(),WebhookDeliveryState.Outcome.RETRYABLE,503,12)).isTrue();var result=delivery(c);if(i<5){assertThat(result.status()).isEqualTo("READY");assertThat(result.nextAttempt()).isBetween(before.plusSeconds(1L<<(i-1)),now().plusSeconds(1L<<(i-1)));assertThat(state.claim(c,true)).isEmpty();due(c);}else assertThat(result.status()).isEqualTo("DEAD");}assertThat(rows("integ_webhook_attempt")).isEqualTo(5);}
    @Test void disabledSenderDoesNotClaimAndRevisionChangeCancelsFrozenPlan(){var sub=create(Uuid7.generate()).subscription();admission.accept(event());var c=candidate();assertThat(state.claim(c,false)).isEmpty();assertThat(rows("integ_webhook_attempt")).isZero();change(sub.id(),1,"PAUSE");assertThat(state.claim(c,true)).isEmpty();assertThat(delivery(c).status()).isEqualTo("CANCELLED");assertThat(rows("integ_webhook_attempt")).isZero();}
    @Test void backlogAdmissionRejectsWholeSetAndLastSlotIsAtomic()throws Exception{
        var first=create(Uuid7.generate()).subscription();
        owner.update("INSERT INTO integ_webhook_event SELECT ?,?,'device.online',gen_random_uuid(),0,repeat('a',64),clock_timestamp(),clock_timestamp(),clock_timestamp(),'ACCEPTED','{}' FROM generate_series(1,9999)",tenant,project);
        owner.update("INSERT INTO integ_webhook_delivery(id,tenant_id,project_id,event_type,event_id,subscription_id,subscription_revision,created_at,deadline_at,status,next_attempt_at) SELECT gen_random_uuid(),tenant_id,project_id,event_type,event_id,?,1,clock_timestamp(),clock_timestamp()+interval '24 hours','READY',clock_timestamp() FROM integ_webhook_event WHERE project_id=?",first.id(),project);
        var second=create(Uuid7.generate()).subscription();var rejected=event();assertThat(admission.accept(rejected)).isEqualTo("BACKLOG_FULL");assertThat(rows("integ_webhook_delivery")).isEqualTo(9999);
        change(second.id(),1,"PAUSE");assertThat(admission.accept(rejected)).isEqualTo("DUPLICATE");
        try(var pool=Executors.newVirtualThreadPerTaskExecutor()){var gate=new CountDownLatch(1);var a=event();var b=event();var one=pool.submit(()->{gate.await();return admission.accept(a);});var two=pool.submit(()->{gate.await();return admission.accept(b);});gate.countDown();assertThat(List.of(one.get(20,TimeUnit.SECONDS),two.get(20,TimeUnit.SECONDS))).containsExactlyInAnyOrder("ACCEPTED","BACKLOG_FULL");}
        assertThat(rows("integ_webhook_delivery")).isEqualTo(10000);
        assertThatThrownBy(()->owner.update("INSERT INTO integ_webhook_delivery(id,tenant_id,project_id,event_type,event_id,subscription_id,subscription_revision,created_at,deadline_at,status,next_attempt_at) SELECT gen_random_uuid(),tenant_id,project_id,event_type,event_id,?,1,clock_timestamp(),clock_timestamp()+interval '24 hours','READY',clock_timestamp() FROM integ_webhook_event WHERE project_id=? AND result='ACCEPTED' LIMIT 1",second.id(),project)).isInstanceOf(DataAccessException.class);
    }
    @Test void dualRlsDeleteDenialAndImmutableTerminalFacts(){create(Uuid7.generate());admission.accept(event());var c=candidate();var claimed=state.claim(c,true).orElseThrow();assertThat(state.finish(c,claimed.token(),WebhookDeliveryState.Outcome.PERMANENT,400,1)).isTrue();for(String table:List.of("integ_webhook_event","integ_webhook_delivery","integ_webhook_attempt","integ_webhook_ingress_state")){assertThat(tx.<Integer>execute(s->{rls.establish(UUID.randomUUID(),project);return jdbc.queryForObject("SELECT count(*) FROM "+table,Integer.class);})).isZero();assertThat(tx.<Integer>execute(s->{rls.establish(tenant,UUID.randomUUID());return jdbc.queryForObject("SELECT count(*) FROM "+table,Integer.class);})).isZero();assertThatThrownBy(()->tx.execute(s->{rls.establish(tenant,project);return jdbc.update("DELETE FROM "+table+" WHERE project_id=?",project);})).isInstanceOf(DataAccessException.class);}assertThatThrownBy(()->owner.update("UPDATE integ_webhook_event SET result='STALE',event_text=NULL WHERE project_id=?",project)).isInstanceOf(DataAccessException.class);assertThatThrownBy(()->owner.update("UPDATE integ_webhook_attempt SET result='SUCCEEDED' WHERE project_id=?",project)).isInstanceOf(DataAccessException.class);assertThatThrownBy(()->owner.update("UPDATE integ_webhook_delivery SET status='READY',terminal_at=NULL WHERE project_id=?",project)).isInstanceOf(DataAccessException.class);}
}
